### ISSUE TITLE
GoPro&Drone photos

### ISSUE THREAD

**Issue by juricagrepo** [alicevision/meshroom#1063]
**Describe the problem**
I captured aerial photos with Mavic pro 2 and ground photos with go pro hero 7 (GPS  was on). Both sets of pictures works perfectly when I run them separately but when i tried to combine them one set fails (Red camera mark). I'm just wondering is it possible to combine those 2 picture sets?

Thanks all.

**Comment by natowi** [comment]
GPS is not supported at the moment. Combining ground photos and drone footage requires enough overlap and image resolution. This depends on your datasets and capturing process. At the moment there is no way to manually align two different reconstructions, but it is on the to do list. 
The next version will include  a manual transformation and alignment tool with GCP (CCTAG) support, so this is something that can be tested in the next release. (Which will be available in a few weeks)

**Comment by juricagrepo** [comment]
Image resolution must be exactly the same? Overlapping and image resolution are the only conditions we need to satisfy to combine those two sets in the same project?

**Comment by natowi** [comment]
> Image resolution must be exactly the same?

No, but it is a combination of multiple factors you need to take into consideration.

Example: An apple on a desk. You capture the apple from a distance of 20cm, the dataset results in a good reconstruction. Now you capture the surroundings in a distance of 2m from the apple - the dataset alone results in a good reconstruction. When combining the two datasets it does not work.
- the area of interest (apple) takes only a small area in the surroundings dataset. This is one problem. 
- If the resolution of the surrounding dataset is too poor, because based on the distance the apple is only a few pixels in the images there is no chance for it to match with the apple dataset and most likely (if anything) only the surroundings will be reconstructed.

If you want to capture a house for example you should make multiple circles around it - from the ground and from the air - and from different distances and at different angles.

**Comment by juricagrepo** [comment]
Okay, gotcha, thanks for the explanation.
