### ISSUE TITLE
[bug] adding multiple folders to "add images" causes hang on Extracting Images metadata and creating Camera intrinsics

### ISSUE THREAD

**Issue by skinkie** [alicevision/meshroom#1079]
**Describe the bug**
When I drag multiple images (from different folders) into meshroom, the second time onwards the application hangs.

![image](https://user-images.githubusercontent.com/502394/95114634-8a09ca00-0744-11eb-8edb-eaaf9a2c332d.png)

**Comment by tkircher** [comment]
Had the same issue with the new release (2023.1.0) - dropped a folder with a handful of images into meshroom and after 24 hours it was still stuck at this dialog with the aliceVision_cam process at 500% CPU. Killing all the processes and restarting, selecting all the images and dropping them in (rather than dropping the folder) worked just fine and took less than a minute.
