### ISSUE TITLE
[bug] Draft Meshing still requires CUDA-capable device

### ISSUE THREAD

**Issue by novemberist** [alicevision/meshroom#1226]
**Describe the bug**

Hello,

the way I understand it, Draft Meshing should work without a CUDA-capable GPU. I followed the steps described in https://github.com/alicevision/meshroom/wiki/Draft-Meshing

However the process always stops at "StructureFromMotion", complaining about the lack of a CUDA-capable device. Am I missing something here? (see screenshot below)

**Screenshots**

![Bildschirmfoto vom 2021-01-15 07-46-37](https://user-images.githubusercontent.com/7927471/104691855-4a6d5980-5707-11eb-986e-0bb58f918b16.png)

**Desktop (please complete the following and other pertinent information):**
Arch Linux / Kernel 5.10.7
AMD Radeon RX580
Meshroom 2019.2.0

**Comment by natowi** [comment]
Please test the default graph with the mini6 dataset https://github.com/alicevision/dataset_monstree

**Comment by seifertm** [comment]
I am experiencing the same issue as the OP: When a load a set of images and compute the StructureFromMotion node in the default graph, Meshroom 2021.1.0 reports missing CUDA capabilities (on a system with an AMD GPU).

> Please test the default graph with the mini6 dataset https://github.com/alicevision/dataset_monstree

When I load the linked mini6 dataset as you suggested, the StructureFromMotion node is computed successfully on the same system. Can you explain why the SFM node behaves differently with different data sets?

**Comment by seifertm** [comment]
Nevermind my previous comment. It turned out the input data set contained too few images. This was the reason for the failing StructureFromMotion node.

A closer look into the logs of the nodes showed that the `cudaGetDeviceCount failed` error appears not only in the _StructureFromMotion_ node, but also in other nodes like _FeatureMatching_. The "error" log message does not cause the computation to stop. It only seems to stop when encountering a _fatal_ error.
