### ISSUE TITLE
Plot features in 2D

### ISSUE THREAD

**Issue by paulparneix** [alicevision/meshroom#123]
Quick feature suggestion : 
It would be nice to have the ability to plot detected features in 2D image view. I use it a lot in other photogrammetry solutions to select the right detector sensitivity for each specific dataset.

Not sure what would be the best way to implement it, C++ QT extension, or pure python solution ?

Thanks.

**Comment by yann-lty** [comment]
This is something we started prototyping and it can actually be done in pure Python/QML, since generated feature files are easily parseable text files - one feature per line with `x y orientation scale` data.
Regarding implementation: the idea is to create a custom QQuickItem (i.e FeatureReader) in Python, taking a path to a feature file through a 'source' property. When this property is set, it loads/parses the feature file and turns the raw text data into a simple model (Python list of dicts, like: `[{'x': 10.1, 'y': 20.5}, {'x': 50.2, 'y': 300.8}]`). On the QML side, this model can then be used in a Repeater over the 2D viewer to instantiate points for each feature.
Hopefully, we'll be able to plug this very soon !

**Comment by natowi** [comment]
[#539](https://github.com/alicevision/meshroom/pull/539)
