### ISSUE TITLE
First model, need feedback on how to improve problem areas

### ISSUE THREAD

**Issue by locque** [alicevision/meshroom#1315]
Hey everyone,
I'm pretty new to photogrammetry and would appreciate some feedback on my first attempt. There a few big problem areas, and I'm not sure what I can do to improve them. I know the lighting is pretty bad, but I'm not concerned with shadows on the textures right now. Could it be affecting the mesh quality though?

![frog-problems](https://user-images.githubusercontent.com/29549891/109850269-9b52f600-7c52-11eb-9f41-1433f9dfea0d.png)

Model on SketchFab: https://skfb.ly/6ZuNM
Dataset: https://photos.app.goo.gl/ZvAi4fFQAENh6NeT8

 - OS: Windows 10 x64
 - Meshroom version: 2021.1.0
 - CPU: Ryzen 5 3600X
 - GPU: Geforce GTX 660
 - RAM: 16GB 3200MHz

**Comment by datavizzard** [comment]
The spot you marked on the pictures points exactly to the area where a lot of reflection takes place.
Avoid surfaces that are shiny, transparent or semi-transparent.

Try to bring the camera closer to the object and change the angle so that there are less reflections on the object. If necessary, draw a white curtain in front of the window to break the direct light.
