### ISSUE TITLE
[question] Release 2021.1.0 shows no GPU while 2020.1.0 version works fine

### ISSUE THREAD

**Issue by hiankun** [alicevision/meshroom#1319]
**Describe the problem**
When using the new release 2021.1.0 binary, Meshroom shows no GPU. In the previous version (2020.1.0), however, the GPU is visible to Meshroom.

- OS: Lubuntu 18.04
- Nividia driver version: 440.33.01
- CUDA version: 10.2

All the tests have been done in the same PC with identical image set.

**Screenshots**
Here is a screenshot in version 2020.1.0. When using 2021.1.0, the UI shows "No GPU".
![2021-03-05-135536_378x602_scrot](https://user-images.githubusercontent.com/7351282/110074932-f4d73400-7dbc-11eb-9876-32300bb2d881.png)

**Additional context**
After extracting the downloaded `Meshroom-2021.1.0-linux-cuda10.tar.gz`, the folder name is `Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2`. Does the `centos7` indicate anything?

**Comment by sannyi** [comment]
I'd report this also on the current Windows version.

    OS: Windows 10 19042.928
    32 GB DDR4 3200@CL16-18-18
    Ryzen 5 5600x
    Python version 3.9 (installed), 3.7 (as dll inside meshroom binary folder)
    Asus GTX 1650 mini dual OC 4GB (Studio ready drivers 462.31 and previous version, actually checked if this could be the reason, but after update is it the same)
    Qt/PySide version [e.g. 5.12.4] : PySide2 folter in the subofolders located
    Meshroom version: downloaded from alicevision site (2021.1.0)
    -No overclock

Relevant links of the conversation in the other bug report.
- https://github.com/alicevision/meshroom/issues/1404#issuecomment-833894537
- https://github.com/alicevision/meshroom/issues/1404#issuecomment-838734812
CUDA information:

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:24:09_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
`

**Comment by sannyi** [comment]
Is this the confirmation that Meshroom uses CUDA? The text below is from 2019.2, because also 2020.1.1 shows "No GPU" for me.
`Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 0
 * input = "D:/ak3900/Osnove_oblikovanja_2021/Projekt_1/MeshroomCaches/kepbor/NK4/MeshroomCache/CameraInit/3ffb2c289b5738f97d904e88e642a72c196c59d6/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "D:/ak3900/Osnove_oblikovanja_2021/Projekt_1/MeshroomCaches/kepbor/NK4/MeshroomCache/FeatureExtraction/c1e6d3a2ffe223e7f771fdf62a2761d08c93fe8e"
 * rangeSize = 40
 * rangeStart = 80
 * verboseLevel = "info"

[11:04:05.418385][info] CUDA-Enabled GPU.
Device information:
	- id:                      0
	- name:                    GeForce GTX 1650
	- compute capability:      7.5
	- total device memory:     4096 MB 
	- device memory available: 3314 MB 
	- per-block shared memory: 49152
	- warp size:               32
	- max threads per block:   1024
	- max threads per SM(X):   1024
	- max block sizes:         {1024,1024,64}
	- max grid sizes:          {2147483647,65535,65535}
	- max 2D array texture:    {131072,65536}
	- max 3D array texture:    {16384,16384,16384}
	- max 2D linear texture:   {131072,65000,2097120}
	- max 2D layered texture:  {32768,32768,2048}
	- number of SM(x)s:        14
	- registers per SM(x):     65536
	- registers per block:     65536
	- concurrent kernels:      yes
	- mapping host memory:     yes
	- unified addressing:      yes
	- texture alignment:       512 byte
	- pitch alignment:         32 byte

[11:04:05.563387][info] Supported CUDA-Enabled GPU detected.
[11:04:05.668385][info] Extracting sift features from view 'D:/ak3900/Osnove_oblikovanja_2021/Projekt_1/MeshroomCaches/kepbor/NK4/Fotke/20210513_173950.jpg' [gpu]
Choosing device 0: GeForce GTX 1650
[11:04:05.980018][info]       11960 sift features extracted from view 'D:/ak3900/Osnove_oblikovanja_2021/Projekt_1/MeshroomCaches/kepbor/NK4/Fotke/20210513_173950.jpg'
[11:04:06.083019][info] Extracting sift features from view 'D:/ak3900/Osnove_oblikovanja_2021/Projekt_1/MeshroomCaches/kepbor/NK4/Fotke/20210411_192147.jpg' [gpu]
[11:04:06.215017][info]       12151 sift features extracted from view 'D:/ak3900/Osnove_oblikovanja_2021/Projekt_1/MeshroomCaches/kepbor/NK4/Fotke/20210411_192147.jpg'
[11:04:06.322018][info] Extracting sift features from view 'D:/ak3900/Osnove_oblikovanja_2021/Projekt_1/MeshroomCaches/kepbor/NK4/Fotke/20210411_192052.jpg' [gpu]
[11:04:06.431034][info]       11990 sift features extracted from view 'D:/ak3900/Osnove_oblikovanja_2021/Projekt_1/MeshroomCaches/kepbor/NK4/Fotke/20210411_192052.jpg'
[11:04:06.433034][info] Task done in (s): 0.869000
`

**Comment by sannyi** [comment]
Could this be only a display error?
On a laptop, i5 7200u paired with a mx940 2GB the following text is displayed (Windows 19042.985,2021.1.0), no statistics are shown, but this is a log (not on all images): [11:30:19.652730][info] Extracting sift features from view 'Fotke/IMG_20210516_193224.jpg' [gpu]
@author, do you see the same?
