### ISSUE TITLE
3d model of tree root not visibile

### ISSUE THREAD

**Issue by rigtm** [alicevision/meshroom#1375]
I have been trying to reconstruct some mangrove tree roots from pictures taken from my phone. I have issues with meshroom not being able to recreate mesh of thin objects like these roots, even though they show up on the previews. These two pictures below show what I mean. I have no issue recreating thicker objects, such as tree trunks bigger than 20 cm in diameter.

I initially started reconstruction with 89 pictures, then augmented it with an additional 69 pictures. All of them were accepted by the program. I did not modify the pipeline. Do you have suggestion on how to improve the mesh I generate? 

![meshroom](https://user-images.githubusercontent.com/82358479/114342062-b556f100-9b8d-11eb-81a5-b85c9efc4842.jpg)
![textured mesh](https://user-images.githubusercontent.com/82358479/114342068-b7b94b00-9b8d-11eb-8102-7647c17b156d.jpg)

Specs: Meshroom v 2019.2.0, Windows 10 , Python 3.6.6, phone Samsung Galaxy S9+

**Comment by natowi** [comment]
Could you check the Mesh prior MeshFiltering? (Double click on Meshing node) If the roots show up there, you need to adjust the Mesh filtering parameters.
Can you enable the FeaturePreview in the ImageViewer (three dots icon in the lower left corner). There are probably not enough features being detected. Did you use the default pipeline? Try to change the describer type to dsp-sift - are the results better?

**Comment by rigtm** [comment]
@natowi Thanks for the suggestions, I will give this a go. I just tried doing [draft meshing](https://github.com/alicevision/meshroom/wiki/Draft-Meshing), which helped to pop some of roots up but not all. Would you recommend changing the describer to dsp-sift while draft meshing as well? What about enabling akaze?

> This is quite a challenging dataset. Did you try other commercial software packages to check if they produce usable models?
No, this is for a big project, and I have already spent too much time successfully creating 3d models of bigger trees and roots (about 60 of them) and I feel that it's too late for me to switch softwares. I'll try my best to make Meshroom work as much as possible.

**Comment by rigtm** [comment]
Update: This is the result of draft meshing: major improvement, but the middle bit of some roots are still missing and end up floating. There are about 200 pictures I used, so I doubt that I did not capture those parts on camera. I usually only use 60-100 pictures to produce excellent quality tree meshes. Someone just suggested that possibly the barnacles attached to the roots are 'blocking' the reconstruction; i.e. they reflect light thus confused the software which part is part of the whole root system. 

![blender](https://user-images.githubusercontent.com/82358479/114503435-e4d62e00-9c5f-11eb-8684-6bd665b1b450.jpg)

**Comment by natowi** [comment]
> I just tried doing draft meshing, which helped to pop some of roots up but not all

That is interesting. Generally, the draft meshing result is not as good as the result with DepthMap.

> Would you recommend changing the describer to dsp-sift while draft meshing as well? What about enabling akaze?

When enabling dsp-sift, disable sift and akaze. dsp-sift performs better on most datasets. 

I would pick a few images from your dataset and do some pipeline variations
- default pipeline
- draft meshing
- default pipeline with sift+akaze
- default pipeline with dsp-sift only

then compare the Meshes from the Meshing node, pick the best result and optimize the parameters before running on the full dataset. Use the "duplicate nodes from here" to branch your graph.
This way you can try how parameter changes affect the quality of your reconstruction.

> I have already spent too much time successfully creating 3d models of bigger trees and roots (about 60 of them) and I feel that it's too late for me to switch softwares.

This questions was not about switching software in general, but more of an "check if this is an dataset issue or not". 
But since your DraftMeshing results are quite good, the dataset seems to be good enough. Larger objects are easier of course, but with the right parameter tweaking we should get good results, too.
https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

> the barnacles attached to the roots are 'blocking' the reconstruction; i.e. they reflect light thus confused the software which part is part of the whole root system.

Yes, this is an possibility. That is why I wanted you to check the feature preview. You would be able to see issues like that quite easily.

**Comment by rigtm** [comment]
> When enabling dsp-sift, disable sift and akaze. dsp-sift performs better on most datasets.

I just found out that dspsift is a new thing on Meshroom2021. This is going to become a different topic, but I tried that version and couldn't get past Feature Extraction when running with a default pipeline.


> I would pick a few images from your dataset and do some node graph variations

This is a very good advice, I don't know why I haven't thought of it and kept running it with full dataset. Thanks. I will be updating shortly.

**Comment by natowi** [comment]
That is really strange. @fabiencastan  any ideas ?

**Comment by natowi** [comment]
From https://github.com/alicevision/meshroom/issues/1380

> I noticed that the 2021.1.0 introduces holes around an object earlier than it was before.

This may come from the new post-processing of the tetrahedralization.
To get previous behavior, change the following parameters on the Meshing node (in the advanced params):

    nbSolidAngleFilteringIterations=0
