### ISSUE TITLE
Export computing to external renderfarm

### ISSUE THREAD

**Issue by adam-bielanski** [alicevision/meshroom#1378]
Hi,
Can someone explain me how to send Meshroom nodes to external renderfarm, please?
Yes, I've read the manual, but it gives absolutely no help for person that never used render farm before, never coded in python/C++.... so I would kindly ask for a step by step instruction, like for dummy. I can declare, that once tested "on my own skin" I can convert these instructions into a chapter to the Meshroom manual.

Thanks in advance.

**Comment by fabiencastan** [comment]
Hi @adam-bielanski ,
Companies can write a submitter as a plugin to use the api of their renderfarm system.
People with multiple machines can setup a mini-renderfarm with opencue or fireworks but it requires to setup a shared storage, etc.

**Comment by adam-bielanski** [comment]
@fabiencastan,
So.... is there any renderfarm that has Meshroom plugin available now? 
A.

**Comment by fabiencastan** [comment]
I do not understand your question. You need to have a renderfarm system, and you can write your submitter to it.

If your question is: Is there is a way available to all end-users to submit in the cloud? The answer is no.

**Comment by adam-bielanski** [comment]
@fcastan , sorry for not being precise, yes, this was my question. I'm not happy to hear it, but maybe someone already did  this for himself... I'll keep looking, as 8t would significantly increase MR capabilities.

**Comment by fabiencastan** [comment]
Yeah I cannot agree more, that would be great to have that integrated natively in Meshroom ;)

**Comment by natowi** [comment]
Here is some documentation on the topic with links to Issues where people  were able to add their own renderfarm https://github.com/alicevision/meshroom/wiki/Renderfarm-submitters
Still, it is not for the casual user as setting up the renderfarm is not an easy task.

**Comment by adam-bielanski** [comment]
Thanks @natowi for the guidance, I'll investigate these paths.
I've asked also a local, relatively small company to support me. Hopefully the use of 800GPU node will sort the dilemma of choosing between precise mesh results and getting them before I die.
I'll keep you posted.

**Comment by natowi** [comment]
My last post was an extended response to what was said before.
"What are they doing differently and how can this be used for meshroom?" is also very non-specific. What does the program do differently? It uses different algorithms or algorithms optimized for speed. How can this be used for meshroom? Not at all, because the commercial programs are closed source. Yes, some commercial packages offer optimized settings for certain workflows, if that's what you mean.

The default graph is optimized to give usable results from most datasets.
The easily accessible parameter tweaks are documented here https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters.

Most of the other parameters are very specific and require a bit more explanation.

Feel free to try it yourself and test out the optimal parameters for indoor datasets.
That's exactly what the node-based interface is for.

> So I wonder how I could reconstruct this dataset anyway.

This is where the GIGO rule kicks in. If, for example, the transitions between rooms have not been sufficiently captured, optimizing parameters won't help either. Meshroom is somewhat sensitive in this respect. However, the error tolerances in some nodes can be adjusted for this purpose. By default, the parameters are optimized for high quality.

> Since these and other problems come up again and again it would make sense to address them in a FAQ.

There are things to document in all corners. As I said, feel free to contribute.

**Comment by natowi** [comment]
>  I'll keep you posted. 

That would be great 👍
