### ISSUE TITLE
node duplication error in the pipeline

### ISSUE THREAD

**Issue by adam-bielanski** [alicevision/meshroom#1389]
**Describe the bug**
Node duplication works  confusing on multiple duplications of the node

**To Reproduce**
1. Go to any node eg. "texturing"
2. Click on "duplicate node"
3. Node "texturing2" appears below "texturing"
4. Go back to  "texturing" node
2. Click on "duplicate node"
3. 3. Node "texturing3" appears directly below "texturing", hiding "texturing2"

**Expected behavior**
New, 3rd node should appear below the last one, not the first.

**Comment by natowi** [comment]
Thank you. I think the issue is being addressed here https://github.com/alicevision/meshroom/pull/1227#issuecomment-819011485

**Comment by adam-bielanski** [comment]
@natowi - I'm afraid auto-layout also requires an update/repair. Try to duplicate various parts of the pipeline eg. first duplicate from meshing, than duplicate from SfM and finally duplicate from feature extraction.
And then try auto-layout.... you'll get a total mess instead of clean, horizontal lines of pipeline. I think in 2020 it worked better.

**Comment by natowi** [comment]
>  And then try auto-layout.... you'll get a total mess instead of clean, horizontal lines of pipeline. I think in 2020 it worked better.

Click on the gear button next to auto-layout and select "maximum" instead of "minimum". 

Default:
![default1](https://user-images.githubusercontent.com/8138537/115583765-7a119c00-a2ca-11eb-8797-c79a8fb9aec8.JPG)

Auto-Max:
![auto-max](https://user-images.githubusercontent.com/8138537/115583771-7bdb5f80-a2ca-11eb-8fb5-f949d1c1542f.JPG)

Auto-Min:
![auto-mini](https://user-images.githubusercontent.com/8138537/115583778-7da52300-a2ca-11eb-8281-4cc354c5441a.JPG)

The Min. layout should be replaced by what is now Max and the Default should become the new Max in my opinion.
