### ISSUE TITLE
Trying out the void technique. Meshroom only renders one face of my object. Is the problem my lighting setup or feature extraction settings? [question]

### ISSUE THREAD

**Issue by cncherno** [alicevision/meshroom#1423]
I'm new to photogrammetry, so if you have any insight or pointers, please share. 

Whenever I render my datasets (60-90 photos), meshroom manages to only render one face of my object or stacks multiple faces on one. 

I struggled to render three passes around an object for this reason so I'm changing settings and only shooting one rotation before importing, trying to get a full pass to render. Being that nothing seems to be working on my end and maybe I don't know what words to search in Google, I'm trying the community.

An aside, I thought the issue may have been the shininess of the object so I coated it in talcum powder for my shoot.

Here are my shots: [https://imgur.com/a/Pwx8Bn8](https://imgur.com/a/Pwx8Bn8)

Here is meshroom's render: [https://imgur.com/a/0SyaNPD](https://imgur.com/a/0SyaNPD)

My camera setup includes a ring flash, CPL filter on my lens, and an Olympus EM1 MarkII with a decent prime lens.
My camera is set to ISO: 200, shutter speed : 10, f10
Meshroom 2021.1.0

Best,
Cncherno

**Comment by natowi** [comment]
Try cleaning up the void:
![CaptureB](https://user-images.githubusercontent.com/8138537/119303639-61e4c200-bc66-11eb-97b8-a6f943732128.JPG)
![Capture](https://user-images.githubusercontent.com/8138537/119303637-614c2b80-bc66-11eb-9112-57ece3f90062.JPG)

Now the reconstruction should be better.

Generally this type of object (simple geometry, few features, large areas with single colour, lightly reflective) should be better modelled than reconstruct (as you have to likely clean up the reconstruction anyway).
It could be quickly reproduced in a specialized tool for packaging: search for 3D Package Mockup Software or packaging design software.
You can achieve good results with blender, too: [example1](https://www.youtube.com/watch?v=Qkj1okN4ZqQ) [example2](https://www.youtube.com/watch?v=zT2dXD2kBKE)

Photogrammetry makes sense for objects that can not be recreated in 3d otherwise easily.
