### ISSUE TITLE
[question] Moving a project between disks

### ISSUE THREAD

**Issue by HarikalarKutusu** [alicevision/meshroom#1451]
**Describe the problem**
As the cache keeps growing, I needed to move the whole directory to another disk.
I found that the project files have references to the files and I did a global find/replace. I did also a multi-file search/replace in the MeshroomCache directory.
That failed.
I think the hash-like directory names in the cache (uid part) are also dependent on the full path, maybe...

Is there a way to move a project's location?

**Comment by fabiencastan** [comment]
It is independant from the image path if (and only if) there is enough metadata on the images to recognize it in a non-ambiguous way (like camera serial number and shooting time).
If there is not enough metadata, the image path become part of the hashes and the source images cannot be relocated.

**Comment by fabiencastan** [comment]
If you only move the meshroom file and the MeshroomCache without changing the sources, it should work fine.

**Comment by HarikalarKutusu** [comment]
Thank you...

It is most probably caused by the "missing" metadata. In some of the images, I had to remove the metadata and add only some of them. See: https://github.com/alicevision/meshroom/issues/1447
On the other hand, after moving the whole directory, I opened each project file and all nodes were grey. I already knew the project file has full paths to the images, so I thought this is caused by the first node. When I checked the UID part of the path, it was pointing to a non-existent location.

Anyway, I decided to put the sources on my media drive and the project files to my development SSD and recalculate with dsp-sift as recommended by @natowi here: https://github.com/alicevision/meshroom/issues/1437 . Constantly creating new test sets + large *.exr files of hundreds of images in multiple projects take lots of space, perhaps this setup will be more performant.

But, I could not pinpoint the path hash calculation in the source code in my first attempt. Is it in Alicevision/core?

**Comment by HarikalarKutusu** [comment]
After separating media and project/cache files into different disks, regenerating all I tested the (non-)issue by renaming the directory and got all green lights.

Awesome! Thank you! Closing...

**Comment by esrat** [comment]
I think the usage of absolute file paths in the project file as well as in other files within the MeshroomCache directory is a big mistake!
There are lots of important use cases where it is necessary to move the data altogether. Just think of disk replacement, no matter to which reason.
All calculations (days or even weeks in my little hobby projects!) would have to be done again!

That's why, **absolute file paths should be replaced with relative file paths!**
These are as unique as absolute file paths for every project file and they don't affect the portability of the data.

**Comment by fabiencastan** [comment]
@esrat Meshroom only uses the file paths if you don't have metadata in your images, which is not common for standard photogrammetry.
Is it your case?

**Comment by msanta** [comment]
I have been trying to move/duplicate a project from one folder to another and it appears that the image paths are used to generate the cache directory UUIDs even though the image(s) have a serialNumber set in the metadata. I used the same image in both folders and I can see that the view ID and camera intrinsic are the same across both projects.

Steps to replicate:
1. Create two folders `A` and `B`
2. Source an image that has a value for `serialNumber` in its metadata and copy it into both folders.
3. Create a project in folder `A` and add the image in folder `A` to it. Run the cameraInit node.
4. Create a project in folder `B` and add the image in folder `B` to it. Run the cameraInit node.

The result (at least for me) is that the cache folders have different UUIDs. When inspecting the camera viewID and camera intrinsic IDs they are the same for both projects.

When I change the image path from the project in folder `B` to reference the image in folder `A` then the cache folder ends up having the same value as in project A.

Therefore it seems to me that Meshroom is using the image path in generating the cache folder UUIDs, which makes it impossible to move projects and referenced images from one place to another without Meshroom generating new UUIDs for the cache folders.

I would appreciate if someone could confirm this is the case.

**Comment by ThePortuguesePlayer** [comment]
I've been needing to move Meshroom projects from one computer to another (Linux AMD system to Windows Nvidia one) and I'm getting a bit frustrated at how the whole process is so needlessly complicated, specially since the logs don't state any reason for when things fail due to wrong directory errors and since there's no documentation about any of this. Most people would have quit by now.

The directories inside the main project file need to be changed, for both input pictures and alicevision components (why these are even here is a bit of a mystery to me, since supposedly, the executable knows from where it's being executed, no?). Inside the cache folder, CameraInit.sfm also has to get its directories updated with a text editor (repeated image paths that are also available in the project file but that for some reason need to exist in 2 different files?). Once you open that project with Meshroom on the new location/PC, Meshroom will ignore all the current directories filled with files and instead create new ones with different paths (again, for some mysterious reason...), to which you have to move the old cache files into, replacing the new ones. If all goes fine, it should work now and you can continue your work. If something goes wrong and the process crashes when you resume your work process, good luck figuring it out, because the logs won't tell you what went wrong 90% of the times even in the debug modes.

Now... Most programs will prompt you for the new location of files when they detect their paths lead nowhere (After Effects/Premiere is a great example). Why does Meshroom make no mention of it? A GUI where you can point to new paths would make the process much faster and user friendly. It's for these "small" things most people will just point at Zephyr Free as the best photogrammetry suite despite its glaring limitations.
