### ISSUE TITLE
[question] Assertion `_vRelativePoses.size() > 0' failed.

### ISSUE THREAD

**Issue by Mikor-mkr** [alicevision/meshroom#1466]
Hello everyone,
thanks for checking out my issue.  For starters, please let me describe what I want to achieve. I want to find it out the relative poses of a camera rig (and their intrinsics if possible). Until I have something working I am using 2 cameras from a rig with their synchronized timestamps and their serial numbers set. Everything seems working ok until this error occurs.

**Problem description**
When I run the CameraRigCalibration it seems to be working until a warning about a frame not being in range pops up and then the following assertion error occurs. 

**Screenshots**
Here is the pipeline:
![image](https://user-images.githubusercontent.com/55749072/124604421-978ae680-de73-11eb-8788-803ec6a2a2b0.png)

Here is how the CameraRigCalibration node is set up:
![image](https://user-images.githubusercontent.com/55749072/124604487-a83b5c80-de73-11eb-9169-5c8c63d3d260.png)
The other nodes are not changed.

**Dataset**
A link will be send in private if someone is interested.

**Log**
```
[2021-07-06 15:45:18.498384] [0x00007fea53cc8880] [debug]   t refined
    1.7881
-0.0981744
    1.4305
[2021-07-06 15:45:18.498405] [0x00007fea53cc8880] [debug]   K refined
 2191.8       0 1026.83
      0  2191.8 1114.94
      0       0       1
[2021-07-06 15:45:18.498458] [0x00007fea53cc8880] [debug]   RMSE = 1.64727 min = 0.2045 max = 4.07797
Localization took  4327 [ms]
[2021-07-06 15:45:18.499146] [0x00007fea53cc8880] [warning] The current frame is out of the range.


******************************
Processed 848 images for camera 0
Processing took 3887.59 [s] overall
Mean time for localization:   4584.42 [ms]
Max time for localization:   6232 [ms]
Min time for localization:   2752 [ms]


******************************
Camera 0 localized 811/848
Rig calibration initialization...
Rig calibration optimization...
aliceVision_rigCalibration: /opt/AliceVision_git/src/aliceVision/rig/Rig.cpp:267: bool aliceVision::rig::Rig::optimizeCalibration(): Assertion `_vRelativePoses.size() > 0' failed.
Aborted (core dumped)
```

**Desktop (please complete the following and other pertinent information):**
 - OS: [Ubuntu 18.04]
 - Meshroom version:
   - Binary version (if applicable) [e.g. 2021.1]

**Comment by Mikor-mkr** [comment]
12 days later and still no luck.....??? Has anyone ever used this node successfully?

**Comment by Mikor-mkr** [comment]
bump

**Comment by Mikor-mkr** [comment]
any ideas?

**Comment by simogasp** [comment]
it seems to me that you are trying to calibrate a rig with only one camera, which is bound to fail because, obviously, `_vRelativePoses` will be empty.

I think the problem is in the `mediaPath` argument that should take as many entry as the number of the cameras of your rig:

https://github.com/alicevision/AliceVision/blob/e85d3cff18340fa839b38d1b4f7df0a79632b2d7/src/software/pipeline/main_rigCalibration.cpp?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L128-L134

It should be rather a list of files one for each camera which will be loaded here

https://github.com/alicevision/AliceVision/blob/e85d3cff18340fa839b38d1b4f7df0a79632b2d7/src/software/pipeline/main_rigCalibration.cpp?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L332-L351

Can you show what's inside your .txt?
