### ISSUE TITLE
[question] What makes a good initial pair?

### ISSUE THREAD

**Issue by Sarkasaa** [alicevision/meshroom#1562]
Let's say I want to turn a figurine into a 3d model, let's also assume that all the pictures I have taken are "perfect" (white balance, exposure, position, subject to background ratio etc.).

Abstract version of the above described example, "F" being the figurine and the numbers being camera positions (top down view):

![Example](https://user-images.githubusercontent.com/44321295/139568091-46dd00d0-6667-4f54-a8dc-d9ebe005d45e.png)

Which two camera positions would you pick for an initial pair, and why?

If it's not that simple, can someone try to show me how they would do it with an example?

Thank you for your time :)

**Comment by simogasp** [comment]
Choosing the initial pair is a complex problem as there are (too) many
parameters involved, and the shape of your object F is one of them.
The general principle is that the two images should have enough overlap,
possibly well spread all over the image (i.e. not just the rightmost part
of one image and the leftmost part of the other, or any other similar
combinations).
This is for the estimation of the fundamental matrix, so that it is well
constrained.
The other important rule is that the distance between the two image points
of view (baseline) is large enough.
So you have to find a good tradeoff between these two rules that impose
conflicting constraints.

Based on your configuration any pair i and i+1 can do it depending on the
actual distance between the cameras and the object F.
With the figure you have here, probably any i and i+2 could do a better
job, but again it really depends on the camera distances VS the distance to
the object. Ultimately, the triangle 1F3 has a larger angle than 1F2, which
allows a better constraint for the 3d triangulation of points. 1F4 is even
better in terms of angle but at that point, you will have a problem finding
good matching between 1 and 4 because the images will be too skew one w.r.t
the other. So 1F3 **may** be a better compromise.

Also, with that particular configuration, I'd rather choose a pair from the
center of the semicircle, say 5-4, 6-4 or 5-3. Once the initial
reconstruction is done, you will start reconstructing both sides of the
pair and that can give better constraints in pose estimation and 3D
triangulation.
But again it's more a heuristic and a rule of thumb, because it really
depends on many other things.

S.

**Comment by Sarkasaa** [comment]
Thank you very much, I finally understand it a bit better now. Now I need to read into how to fully reconstruct a 3d object instead of just one face. I seem to have issues finding matches once I go over the 180° line, but I'll figure it out :)

Thank you for your time!
