### ISSUE TITLE
Which 4 distortion parameters are needed for a fisheye camera?

### ISSUE THREAD

**Issue by Michael-Manning** [alicevision/meshroom#1713]
Related:
https://github.com/alicevision/AliceVision/issues/45
#921 
#1484 
#1647 
#1649 

I am attempting to apply the distortion parameters created by the CameraCalibration utility/OpenCV to the CameraInit node for a fisheye camera.

The CameraCalibration utility provides:

- image size
- focal
- principal coordinates
- K1 K2 K3 radial distortion coefficients

Additionally, OpenCV will provide the p1 and p2 tangential distortion coefficients.

The common theme among all the related issues is that the parameters should be applied in this order:
0 - k1
1 - k2
2 - k3
3 - p1
4 - p2

However, as pointed out in #1649, the camera type you select might be what determines which distortion parameters are required. The camera type tooltip states that radial3 contains the 3 radial distortion parameters and that brown uses the additional 2 tangential parameters. This is all coherent with the linked issues related to this topic, but what about fisheye cameras which require 4 parameters?

How do I Identify and acquire the 4 distortion parameters for a fisheye camera?

Thank you

**Comment by simogasp** [comment]
In opencv k4-k6 are not radial distortion coefficients, they refer to other coefficients in the Rational model.
https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga3207604e4b1a1758aa66acb6ed5aa65d
That's why the message sounds ambiguous. Only K1 K2 K3 will be taken into account. If you pass cv::CALIB_FIX_K4 it will only take into account if `CALIB_RATIONAL_MODEL` is also passed.
So it's better to pass only 3 radial distortion coefficients and, possibly, 2 tangential coefficients.

That being said, it also depends of what kind of fisheye you are using, fisheye camera are rarely well modeled by a pinhole camera with the radial+tangential distortion unless the distortion is mild.

**Comment by Michael-Manning** [comment]
This makes sense.  Now I think the model I should really be using equidistant_r3 model anyways (the initial pair isn't found when I use this setting but that's a different issue)

Thanks for answering my question

**Comment by qume** [comment]
> This makes sense. Now I think the model I should really be using equidistant_r3 model anyways (the initial pair isn't found when I use this setting but that's a different issue)

I'm having the same issue with the initial pair using the equidistant_r3 model. Did you manage to find a way around it?
