### ISSUE TITLE
[question] Got error when run meshroom_batch

### ISSUE THREAD

**Issue by Twilight89** [alicevision/Meshroom#1900]
Environment：Ubuntu20.04， build AliceVision and meshroom， try to run in the command line.
The command：python3 bin/meshroom_batch -i ./dataset_monstree/mini3/ --toNode DepthMap_1 -o ./test_result/，it got error：
RuntimeError: meshroom_batch requires a pipeline graph with exactly one 'Publish' node, 0 found.

I have no idea where is the "Publish" node and I searched the issues but no related one.
Hope for reply~

**Comment by hammady** [comment]
This bug is caused by this commit: 8fb0c778d12af5d3d51567407a6d38132e53d796 where the hardcoded pipelines were converted to a JSON description for a new format (.mg).
I inspected the default  pipeline `photogrammetry` and verified that it has no node of type `Publish`. However, in the above commit there was a code to add this node programatically:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/855847/220530651-9863aed7-e1e7-42e3-82d1-b79fe5d92ef3.png">
The fix is to describe this omitted code in the pipeline file correctly. I am trying this now and will create a PR if successful.
