### ISSUE TITLE
[bug] Crash when importing images from non-ASCII path.

### ISSUE THREAD

**Issue by alexandre97costa** [alicevision/Meshroom#1988]
**Describe the bug**
Crash when importing images from non-ASCII path.

**To Reproduce**
1. Open Meshroom;
2. Import images either by drag-and-drop or via File -> Import Images;
2.a The images need to be in a folder with non-ASCII characters, like "ç" or "ã".
3. The program will eventually show a loading operation;
4. The program crashes.

**Expected behavior**
To import images from any path, regardless of being ASCII compliant or not.

**Screenshots**
N/A

**Log**
N/A

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Meshroom version: 2023.2

**Comment by TheCell** [comment]
Happened to me aswell on Windows 11, Same Meshroom version. I had an "ä" in my Path.

**Comment by natowi** [comment]
https://github.com/alicevision/Meshroom/issues/2139

**Comment by cbentejac** [comment]
This issue is fixed by alicevision/AliceVision#1629. 

Meshroom 2023.3.0 does not crash anymore when importing images that contain non-ASCII characters in their paths, but the subsequent nodes cannot run correctly with them. The next release will integrate alicevision/AliceVision#1629 and fully support images with non-ASCII characters in their path.

**Comment by alexandre97costa** [comment]
Thank you! @cbentejac
