### ISSUE TITLE
[bug] Cannot finish computing of pipeline after crash

### ISSUE THREAD

**Issue by mcDandy** [alicevision/Meshroom#2049]
**Describe the bug**
Some cannot be in in EXTERN because of unresolved dependencies
Nodes which are ready will be processed 

Nothing will be processed.

**To Reproduce**
1. Start a pipeline
2. Fill up the drive completly
3. meshroom should crash
4. load pipeline which crashed
5. see error

**Expected behavior**
I am able to continue pipeline

**Screenshots**
![image](https://github.com/alicevision/Meshroom/assets/18588943/b9d273e4-fa99-4a2a-9328-f04e01e76158)

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )
No log generated

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ] windows 11
 - Python version [e.g. 2.6] 2.7.4 (I have 3.9 and 3.11 installed)
 - Qt/PySide version [e.g. 5.12.4] the one built in meshroom (none installed)
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1] 2023.1.0
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by cbentejac** [comment]
Hi @mcDandy,

Since Meshroom crashed while the nodes were being computed, their status remains "computing" (and will never be updated again) and when a new instance of Meshroom is opened, it is assumed that these nodes are still being computed in the first Meshroom instance (hence the "EXTERN" status, shown by the little cloud icon on each node).

To unlock the situation, you can use the "Force Unlock Nodes" option followed with a "Clear Pending Status". Both options are available in the Graph Editor through the button shown below:
![issue github](https://github.com/alicevision/Meshroom/assets/11963329/06a76f98-7d8e-423b-83da-364a377f7c0e)

Once the nodes' status has been cleared, you should be able to start computations with them again.

**Comment by mcDandy** [comment]
Thank you.
