### ISSUE TITLE
[bug] Python error - no module named codecs

### ISSUE THREAD

**Issue by TerenceChen95** [alicevision/Meshroom#2194]
**Describe the bug**
I tried to open windows executable 'Meshroom.exe'  and encounter the following bug.
![image](https://github.com/alicevision/Meshroom/assets/24600576/610b369f-2c64-447a-ae93-23b9c7541b38)
The library points to a unknown path in my computer. I also noticed the existance folder of /root/lib/encoding/, but missing the codecs.pyc  maybe?

**Comment by natowi** [comment]
Did you download the zip from here https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2023.2.0-win64.zip and extracted the zip afterwards?

**Comment by TerenceChen95** [comment]
Thanks for reply! I download the zip from the given link and still got the same error. I start to wonder if it needs write authority for specific paths.

**Comment by natowi** [comment]
Hmm, maybe something from here can give an idea? https://github.com/alicevision/Meshroom/wiki/Troubleshooting

**Comment by cbentejac** [comment]
Hi @TerenceChen95,

Do you have Python installed on your computer? Meshroom is packaged with a version of Python (3.7) that normally includes everything needed to run, so you shouldn't have this error. My guess would be that there's a conflict somewhere ("codecs" is a standard package that comes with any Python installation, so it is not missing because it hasn't been installed).
