### ISSUE TITLE
Beginner, Always get horrible result

### ISSUE THREAD

**Issue by ChibiFable** [alicevision/Meshroom#2460]
**Describe the problem**
Hello,

I tried for the first time to generate meshes with Meshroom 2023.3.0. I use a white fabric background, an electric rotation plate to photograph 360° the object and softbox lights in the background. The result is always horrible, no matter how many pics i shoot 95-300 from all different angles. Also if the genertion is finished i dont get any option to show the mesh, only see the points of the structure of motion and the camera positions seems all wrong. IDK what i did wrong. Can you guys help me?

**Screenshots**
Meshroom after generetion: https://i.ibb.co/tHB8ybY/Meshroom.jpg
Result: https://i.ibb.co/Tq5hSNL/Result.jpg

**Dataset**
These image sets i used (Plant & Bottle): https://drive.google.com/drive/folders/1mYBmlNOHANDqwWazuC7nj57CdwLZhEfr?usp=sharing

**Comment by msanta** [comment]
There are a few issues:

1. Background features are visible while using a turntable. Photogrammetry works by finding features, then matching features between images and then calculating the change in position of the camera viewpoints based on those features. In your images the edge of the white cloth can be seen on the floor which creates a lot of good features. Features will also be detected on the floor, the cable that connects to the turntable and folds in the cloth. The effect is that the feature matching step is getting conflicting information (the features on the plant are moving but the background features are nearly static). You should aim to eliminate as much of the background as possible if you are using a turntable.

2. Your subject needs to take up as much of the image as possible to get as many features resolved as possible. You need to get closer to it and if possible use a different aspect ratio (3:4 or 1:1). This will help with reducing the number of background features.

3. Objects that have very few features will be difficult to reconstruct. This is the case for the bucket and the plant pot. One solution would be to apply some dust to give the surfaces some features.

4. Take individual photos rather than extracting frames from a video. A video will result in the loss of features and adds compression artifacts. When using a phone to take photos turn of all photo enhancement settings.

It might be worth trying simple objects first (something with lots of features), like a rock.

**Comment by ChibiFable** [comment]
> There are a few issues:
> 
>     1. Background features are visible while using a turntable. Photogrammetry works by finding features, then matching features between images and then calculating the change in position of the camera viewpoints based on those features. In your images the edge of the white cloth can be seen on the floor which creates a lot of good features. Features will also be detected on the floor, the cable that connects to the turntable and folds in the cloth. The effect is that the feature matching step is getting conflicting information (the features on the plant are moving but the background features are nearly static). You should aim to eliminate as much of the background as possible if you are using a turntable.
> 
>     2. Your subject needs to take up as much of the image as possible to get as many features resolved as possible. You need to get closer to it and if possible use a different aspect ratio (3:4 or 1:1). This will help with reducing the number of background features.
> 
>     3. Objects that have very few features will be difficult to reconstruct. This is the case for the bucket and the plant pot. One solution would be to apply some dust to give the surfaces some features.
> 
>     4. Take individual photos rather than extracting frames from a video. A video will result in the loss of features and adds compression artifacts. When using a phone to take photos turn of all photo enhancement settings.
> 
> 
> It might be worth trying simple objects first (something with lots of features), like a rock.

Hi,

thanks for the answer. It seems that for my purpose photoscanning is the wrong way. Cause all object i needed i cant scan. Nature asset i have a lot already.

Nevertheless thanks for the reply.

Greets
