### ISSUE TITLE
Stuck at MeshFiltering (Graph is being computed externally)

### ISSUE THREAD

**Issue by Lemente** [alicevision/meshroom#249]
Hello

I let MeshRoom run during the night, and when I woke up, it was stuck at MeshFiltering. It was fully orange, and the "start" button was greyed. It was using aroung 5% of my CPU. Not sure about the memory/GPU, maybe 20%. When I hit "stop", the CPU usage dropped.

I saved and restarted my computer. I opened the project, but now both "Start" and "Stop" are greyed out, with the mention "Graph is being computed externally".
All step are green up to "Meshing", "Meshfiltering" is still orange. I cannot hit "Compute" on any of the step.
All the files are still in the MeshroomCache folder, and I was able to open the .obj file in the Meshing file in Blender.

Can someone explain any of this to me? How can I go one with that project?

My specs :
W10 64bit
GTX 970
i7-4790K
16Go of RAM

The project is using 88 frames/cameras (4608x3072).

Here is the console content at the restart.
`Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")`

I was already able to successfully generate a 3D model just before that (with less frames).

Anything else you need to know?

Thanks!

**Comment by ChemicalXandco** [comment]
I heard that this can be fixed by clicking on the bad node, And in attributes click on the cog then 'Clear Submitted Status' 
![tempsnipclr](https://user-images.githubusercontent.com/32775248/45598040-1fef2280-b9cd-11e8-9a54-257a687a5a89.png) Then you should be able run that node again. Let us know if this works.

**Comment by mmiiqquueell** [comment]
It happens to me at each node, pressing Stop and Start continues but when it reaches the node Structure from motion and next nodes it doesn't continue. This happens in Windows 7, Thanks to a user who already answered a previous topic, it indicates that you can continue manually editing the Status file of each node once the processing is finished. The only problem is .... when I wanted to do the test I did it with 57 images, I lost approximately 2 hours manually changing each status file to see the final result, which was a disaster since I made it from a toy car with crystals and the program doesn't detect crystals (logical). Now I wanted to try from a game whose camera rotates around the character, the problem is that there are 3400 images (I reduced the size of the images and the quantity), I recorded a video and I passed it to jpg images, cutting only the center where the character and the framerate of 60 to 15 Frames, you save a lot of time from capture to capture. But there are still many images, I have been an hour for the first node that gets stuck every time and there are almost 84 calculations, I do not want to think how long it will take when I get to the Structure from motion node which took almost an hour with the car that prove at the beginning.

For this reason I prefer to wait for an update to fix this failure and not have to waste all day making the changes from the Status file every moment.

The Clear data (from node or status) that says Chemical doesn't work because yes, you can delete the cache but it doesn't matter, when it finishes it will get stuck again.

Of course I must say that of all the PhotoScaning programs that I have tried, this is the best and also its free.

**Comment by ChemicalXandco** [comment]
It might be related to #183 but there is no mention of it locking the start button.

**Comment by mmiiqquueell** [comment]
> 
> 
> It might be related to #183 but there is no mention of it locking the start button.

Yes, and this is the solution (manual):
https://github.com/alicevision/meshroom/issues/183#issuecomment-414952460

The start button I don't know how it works exactly, sometimes it's blocked and sometimes not, when that happens I close the program, delete the entire folder (cache folder) and start over again and replace the saved file. Since otherwise it gets stuck and you can't do anything, the program stuck saying "it requires an external tool" or something like that...

**Comment by BKLronin** [comment]
I had a similar issue and I also cleared the submitted statuses of the following nodes. That enabled the play button for me.

**Comment by Anar91** [comment]
Hi,
it also happens to me on Windows10.
I'm using command line instead of the GUI but computation will stop after some node without calling the next one with no reason (last computed node having status "SUCCESS"). Most of the time it will happen during the DepthMap node where it will only compute them one by one (stopping after each one).
So I have to kill the task and launch it again with --toNode DepthMap_1 and --forceStatus flags in the command line.
I'm using command line because I want to automate the full scan and reconstruction process but I'm stuck here because of this issue.
Otherwise it's a wonderful program that can produce very good results !
Congratulation.

**Comment by Darker** [comment]
This exact thing happened to me. "Clear submitted status" does not solve it.

**Comment by DerTee** [comment]
@BKLronin 
> I had a similar issue and I also cleared the submitted statuses of the **following** nodes. That enabled the play button for me.

Thanks man! I didn't get that I had to clear the status of **every single node that is in line after the stuck one!** Even the nodes that were not orange or in progress! That took a while :)

**Comment by fabiencastan** [comment]
You have a menu on the top-right of the graph widget with "Clear Pending Status" to do it on all nodes at once.

**Comment by silycr** [comment]
I just encountered the same thing. 
The processing stalled at StructurefromMotion with no errors. Program hang after hitting start. Re-opened the program and the project, only to receive message 'the graph is being computed externally' preventing start.
@BKLronin Thanks you. Clearing all the pending status of each node after SfM reactivated the start button.

**Comment by brtbt** [comment]
For me also got stuck at mesh filtering node... Any solution... I don't want to start again meshing from scratch
... Pls help out

**Comment by fabiencastan** [comment]
What is your log file with `verbose=trace`?
Have you tried to reduce the number of iterations?
