### ISSUE TITLE
Build MeshRoom

### ISSUE THREAD

**Issue by 1992Zz** [alicevision/meshroom#267]
I have configured the relevant library, and the EXE file can also run, but there is no SFM module in the interface.Open files can only be selected in.Mg format, and no other formats such as JPG can be selected.I hope you can give us guidance, thank you.

Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[2018-10-11 19:00:20,973][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

**Comment by ChemicalXandco** [comment]
I don't know why you posted the startup log, but see #114 for an explanation about his message. In order to assist, are you using the [binary release](https://github.com/alicevision/meshroom/releases) `2018.1.0` or did you compile yourself? And on what platform are are you running on?

Meshroom project files are stored with a .mg file extension, and the actual files such as the sfm, depth maps and mesh are stored in the `MeshroomCashe` folder which is usually in the same directory as the project file.

You can load a saved project by using the open in the file menu, as you described. It is expected behavior, however, to not be able to load any kind of picture files using this method, as they are not project files.

In order to load images into the reconstruction pipeline of the current session, you must first select the images you want to load (in file explorer if you are on windows) and drag them to where it says `Drop Image Files / Folders` on the meshroom ui.

**Comment by Randal7** [comment]
[2018-12-14 10:01:27,062][WARNING] == The following plugins could not be loaded ==
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
  * simpleFarmSubmitter: No module named 'simpleFarm'       How to solve？
