### ISSUE TITLE
Using a turntable. How?

### ISSUE THREAD

**Issue by hysteric77** [alicevision/meshroom#283]
Is there a setting I need to change to get the program to work correctly when using a turntable and rotating the object instead of moving the camera around the object?

What I am ending up with is a final mesh with with just the front of the intended object, and then my large empty off-white wall in the background.

When the point cloud comes up, its shows all the camera locations in two cluster spots (basically straight ahead, and then slightly higher angled downwards... the two basic angles I intended for it to use.)

I used 34 images, so I guess basically 17 images at each of the two front camera positions.  The complete 360 degree rotation of the object is covered by the images.  The images are all checked green indicating that they've been reconstructed.

I've gone through about every rough draft documentation, tutorial video, issue database, etc I can find, but I haven't found any sort of solution for this.   The rough draft manual does mention using a turntable, and/or rotating an object, about four times... but it doesn't give any indication on how to get it to function correctly.

I can get reasonably good results by moving the camera around an object.. so even though I am relatively new to photogrammetry I do have a general idea of how it all works.

Perhaps I am missing something simple, but I've been through all the nodes and settings and don't see anything that gives me the option to tell the program I am using photos in which the object is rotated, as opposed to the camera being moved around the object.

Attached is an image of the final result... a screenshot from Blender at an angle.  (The actual camera location was pointed perpendicular to the wall).  The object is a garden gnome, about a foot tall.  On a turntable.  An actual record turntable from the 80's!! that I'm currently just manually rotating.  The background is just an empty wall, about six inches behind the location of the gnome.

I'm using a Moto G5 Plus for the camera (it's the best I have... I'm not a photographer) and I realize my lighting is rather poor.  My rig is a i7 8700, 16gb ram, with a 1070ti (8gb vram) running Windows 10.  And again, I've been able to get proper results when moving the camera around the object.

Oh, and I'm using all the default settings EXCEPT on the MeshFiltering node I've unchecked "Keep only the largest mesh."  (An earlier result didn't even have the gnome at all, just the large background area.)

Any help is greatly appreciated!  Thanks!

![meshroom_issue_garden_gnome](https://user-images.githubusercontent.com/44490211/47550109-033ee800-d8b3-11e8-9830-54f83ce1eea4.jpg)

**Comment by ChemicalXandco** [comment]
Have you ever heard about masking? Currently, meshroom does not support masking but you can see #188 for a decent workaround. 

Essentially, the software is detecting features on both the foreground and background. On a turntable, the subject is moving but the background is not. This confuses it. So you have 2 choices: make the background completely white and same lighting so that no features can be extracted from this region, or mask your images - that is basically covering the background artificially to stop the region being used in the pipeline, or both.

**Comment by marcfielding1** [comment]
Sorry to nudge this but there's an easier way - check this out - https://youtu.be/nWh51Ipp5Sc?t=449

You CAN use a turntable easily, best way is to buy one of [these](https://www.amazon.co.uk/FOSITAN-Portable-Photography-Adjustable-Background/dp/B07ZRB73BK/ref=pd_sbs_421_3/259-2033450-3373734?_encoding=UTF8&pd_rd_i=B07ZRB73BK&pd_rd_r=a240858a-071a-4f63-ab42-521c2980ac59&pd_rd_w=7tpfp&pd_rd_wg=qlr28&pf_rd_p=f4a31d1d-8f61-48f5-b6f4-a22ba06df575&pf_rd_r=5PW3ADE1HYXRZ826Y1Z9&refRID=5PW3ADE1HYXRZ826Y1Z9&th=1)

Then follow the instructions on the video, basically you make sure your background has NO FEATURES, then put a plate on top of your turntable to obscure the turntable but secondly to provide a reference for the software to work.

**Really rough example, I literally just made this...**

I made this from a cereal box and got my kids to draw on it..

![Image from iOS](https://user-images.githubusercontent.com/2651211/70351651-537fcc00-1861-11ea-9cea-30d404c97a9c.jpg)

Then I placed a piece of paper behind the turntable...

![IMG_0645_1](https://user-images.githubusercontent.com/2651211/70351707-6d211380-1861-11ea-8660-e281fb35b733.jpg)

I then took two 10 second videos, one from an elevated angle, one at a 90 degree angle. I then split them into frames - around 600 images in total. You probably don't made that many images, if you haven't got a decent GPU just extract less frames.

If you notice I messed up - you can see a the container holding the piece of paper up in the top of the image and in the bottom you can see the turntable.

Dragged them into Meshroom and ran it, now the results aren't perfect because it's not in the tent(above), the lighting isn't great and there's pollution from the turntable and the rice container, but you can see how you can easily make it work with non cereal box, kiddy drawn kit.

You'll notice that a lot of cameras are missing, thats because the turntable and rice are visible and static so the software thinks that it should be reconstructing it and getting confused.

![Screenshot from 2019-12-06 19-59-53](https://user-images.githubusercontent.com/2651211/70352414-03096e00-1863-11ea-879c-cfb9dcc248ba.png)

**End Result**
Now this looks pretty shakey BUT I promise you it's easily fixed without a 5 minute knock up solution...

![Screenshot from 2019-12-06 21-23-02](https://user-images.githubusercontent.com/2651211/70357408-bd52a280-186e-11ea-9a3a-057a488b83a3.png)
