### ISSUE TITLE
(86x)

### ISSUE THREAD

**Issue by mestry55** [alicevision/meshroom#286]
could some one please build for a 86/32bit win7

**Comment by natowi** [comment]
If you need a 32bit build for win7 you will have to build it yourself. 32bit systems are out of date and so is windows 7. Building for 32bit might get difficult, as some libraries in the dependencies may no longer provide 32bit versions. Also 32bit systems can not make use of more than 4 GB RAM! 
So even if you were able to get a working Meshroom version for Win7 32bit, it would be worthless due to bad performance on such a system.
