### ISSUE TITLE
Please add camera model(s) and sensor width(s) in the database.

### ISSUE THREAD

**Issue by chriscatwhovian** [alicevision/meshroom#291]
i saw this from a video and now it isnt working mabey you updated it since then but when i press start it says [error] Please add camera model(s) and sensor width(s) in the database. the video was https://www.youtube.com/watch?v=k4NTf0hMjtY&index=7&t=1607s&list=PLYMfFKFp2bIb7rp0F9ggBsvu8vvch2-uN

**Comment by natowi** [comment]
You need to add your camera sensor to the database.
Please read: https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database

**Comment by chriscatwhovian** [comment]
why is this necessary i cant figure this out

**Comment by natowi** [comment]
Meshroom uses a sensor database to get initial parameter for the photogrammetry pipeline.
The sensor database does not contain _all_ camera sensor parameters, so like in your case you have to add this by yourself as it is described in the wiki. At the moment this requires some manual editing of the sensor database. The next Meshroom version will simplify this process.

**Comment by chriscatwhovian** [comment]
oh ok so how long till you think it will take to update? or do you not know?

**Comment by natowi** [comment]
The next release of Meshroom is in progress but a release date has not been announced. 
I guess you´ll have to wait at least a few months for the next release. 
However you can use Meshroom now, as I described before/in the wiki.

**Comment by GlOwl** [comment]
Had the same problem and finally got around this error by just adding the camera brand/manufacturer and model like stated in the wiki, but i had to include every space character in the line from the log into the database, otherwise it would pretend not to know the model!

**Comment by fabiencastan** [comment]
The problem with spaces in the DB is now fixed.
The UI to update the DB is on the todo list, but not for the next release.

**Comment by oo5p4c3oo** [comment]
First, sorry my english ...

I tried two way ,but a second way working ..
my camera SONY xz premium 
camera database line : https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/cameraSensors.db#L1
at 6211 

Sony;Sony Xperia XZ Premium;4.69;devicespecifications

searched the C:\******-\Meshroom-2018.1.0-win7-64\aliceVision\share\aliceVision\camerasensors.db file 
open it for notepad
i not find my phone in the list ,ok i ctrl+c the github cameradatabase ( my phone ) line and (insert) ctrl+v in my  cameradaatabase db file . test it .
ok it is working but just half 
the import working but the  prompt window is get error message 
" add camera and sensor size"
ok try second .
in the github camera database list my camera:
Sony;Sony Xperia XZ Premium;4.69;devicespecifications
and the exif info ( camera type in my jpeg is : G8141 
So i change my cameradb info : 
Sony;G8141;4.69 
and try it  WORKING :)  now testing hard :)

**Comment by maexfran** [comment]
Greetings! 

 I hope you can give me a hand with this, I don't know what else to do and I can't get this working. I have a Fairphone 3, which is correctly listed ( sensor size included ). Still, it doesn't recognize the camera. I'm shooting with a fork of Open camera ( Fairphone 3 + e | project ) in png. Do you know why it still fails? 
Thanks in advanced

**Comment by JordMa** [comment]
Hello, everyone,

we have a DJI Mavic 3 Enterprise 3E/3T drone.
The images are displayed in the Meshroom with the "Error" Senor Widt: (undefined (estimation: 6.345770).

Unfortunately, I don't know what I have to enter in the database here so that Meshroom can correctly recognize the camera of the drone. Can someone please help me here? thanks

**Comment by fabiencastan** [comment]
Here is the latest version of the sensor database:
https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/cameraSensors.db#L1438
Check if the version of your DJI is included.
You can see in the Meshroom warning the exact name of your camera model.

**Comment by JordMa** [comment]
Hi,

No, the drone is not yet in the existing database - it only came onto the market a few weeks ago.

The following is displayed in the Meshroom:
![screen](https://user-images.githubusercontent.com/122679286/212474722-37c74f5f-d5d1-44db-83ca-fe525c81704c.jpg)

**Comment by JordMa** [comment]
Hello, can no one help me here?

**Comment by fabiencastan** [comment]
https://github.com/alicevision/AliceVision/pull/1333

**Comment by JordMa** [comment]
I made the entry in the data nak on the PC, restarted the Meshroom - but it didn't change anything - the same display continued to die as before

**Comment by JordMa** [comment]
Sorry my mistake - should have read the link first - works THANK YOU!

**Comment by ryanholloway123** [comment]
Hello, I am attempting to use Meshroom with a Canon EOS R5, and while the camera is currently located in the database (line 695) and Meshroom is properly identifying the make and model of the camera, it is still not displaying/receiving the 'SensorWidth'. Can you possibly think of a reason for this? And is there any solution?

![Canon R5 in database](https://user-images.githubusercontent.com/126986567/222928257-4f6af372-b364-470d-82f9-18a7c4fdb2cd.png)

![error message - metadata issues](https://user-images.githubusercontent.com/126986567/222928437-29f94cbd-1fc4-4c8c-a43c-9a1dc4b0255b.png)


A separate issue is the focal length data is not in my metadata due to using a manual lens. The best workaround I have found is to edit the metadata using ExifTool. Will there ever be an option to manually enter in the 'FocalLength' and 'FocalLengthIn35mmFilm' data within Meshroom? This feature would enable the use of manual lenses without the need to use ExifTool to edit the Metadata.

**Comment by ryanholloway123** [comment]
I was able to manually enter the 'Focal Length' and 'FocalLengthIn35mmFilm' data by using ExifTool, which then provided a 'SensorWidthEstimation' value calculated within Meshroom, which is almost exactly accurate (likely just some floating point errors), as the sensor size is 36mm and the estimation from Meshroom is 35.994591. 

I was hoping this would make the pipeline compute properly since the error indicator had changed from red to yellow, but unfortunately, the HDR's are rending out completely white, which is what was happening before I added the focal length data.

![HRD's are still all white - after changing focal length](https://user-images.githubusercontent.com/126986567/222932590-bc9635b2-ab66-4fe7-a355-9efc119ab8b2.png)

Do you possibly know why the HDR's would be all white? If so, do you have any solution?

**Comment by alexthemc1** [comment]
Bonjour, je débute dans meshroom et je rencontre un problème "camera : not reconstructed". (la camera est rouge et barrée)

Je travaille avec un appareil Fujifilm XS10;23.5 , seulement quand je l'inclu manuellement dans la database, il n'est toujours pas reconnu... 

voici deux printscreen: 
![Capture d’écran (9)](https://user-images.githubusercontent.com/131371101/233382539-358cdc8a-3aba-4fcb-94e8-e4fba04faf53.png)
![Capture d’écran (8)](https://user-images.githubusercontent.com/131371101/233381042-fcd9ffb2-17f1-4292-9074-3459150beaf7.png)

**Comment by alexthemc1** [comment]
![Capture d’écran (10)](https://user-images.githubusercontent.com/131371101/233389223-05f5c367-2546-4047-a734-b2c792a5fa0e.png)
it's my camera on : https://www.digicamdb.com/specs/fujifilm_x-s10/

**Comment by mugulmd** [comment]
Hi @alexthemc1 !
The role of the StructureFromMotion node is to determine the pose of the camera for each viewpoint, so basically guessing where was your camera (in 3D space) when you took the picture.
This has nothing to do with finding the camera in the database: "camera not reconstructed" means that the engine failed to compute these poses.
Retrieving the camera poses is a key step in 3D reconstuction pipelines, so if none of your cameras were reconstructed then you won't be able to complete your photogrammetry...
I see you only have 3 images in your dataset, and the object you're shooting is glossy, so you probably won't go very far with that, sorry. However there are plenty of tutorials online on how to do a good shooting for photogrammetry 😄
