### ISSUE TITLE
How can I make all photos calibrated for Meshroom?

### ISSUE THREAD

**Issue by Rado235** [alicevision/meshroom#345]
Hello! A few days ago I just found out this amazing program! I really liked it, but I got a problem. I took about 30 pictures of my car and only 5 of them were with a green thick on their top right corner. I want to use all the photos I took and is that possible I tried changing Describer Preset to Ultra in FeatureExtraction node and putting TextureDownscale option to 1 in the  Texture node but still not callibrating the remaining 25 photos. I hope that you can help me fast!

**Comment by ChemicalXandco** [comment]
A car is a very hard thing to scan because it has lots of reflections that confuse the software. If you really must scan a car try getting a really muddy car or cover it in painting tape or something that won't reflect too much and it is recommended that you put features on it to be detected, not just like a blank sheet. If you are scanning a glossy object indoors where you can control the lighting, diffused lighting can help.

**Comment by Rado235** [comment]
What kind of features,sorry?

**Comment by hargrovecompany** [comment]
If you're using a hand held camera, and the car is under lighting that you might see at a car show, it's going to practically impossible.  A reflection of something that would be a feature in given image will be in a different location on the vehicle in photos taken adjacent to one another.  
I think a hand held laser scanner is probably the best tool for that type of thing....unless, as said above, you apply dust to the car to give it a surface that's as non-reflective as possible.  There are products made specifically for that purpose.

**Comment by Rado235** [comment]
Maybe in photoshop? Haha
