### ISSUE TITLE
20% GPU used for rendering of the window?

### ISSUE THREAD

**Issue by Darker** [alicevision/meshroom#367]
When I have the window with Meshroom open, even when no process is running, it uses up to 20% GPU. No other window on my system has such consumption.

I have Win 10 Pro. My GPU is NVIDIA GeForce GTX 1060 3GB. Single meshroom window uses as much of it's power as most 2010-2015 games. When I minimize Meshroom, GPU usage goes to 0%, so I am really sure it's in the rendering.

**Comment by edtechchrward** [comment]
I get high GPU usage  as well. As in the @Darker's post this happens when the Meshroom window is open and even when no tasks are running. The high usage stops when the Meshroom window is minimized.

I have Win7 Pro. with  NVIDIA NVS295 (CUDA 1.1) rendering the screen and showing the load mentioned above.  As an aside, I also have a Tesla C2075 (CUDA 2.0)  installed and working (Blender 2.79b uses it), but this unit is not used at all by Meshroom so my pipeline stalls when the CUDA GPU is needed for computing the depth map. This is a pity as I was depending on the Tesla to take the CUDA computing workload!!

I've done some CUDA programming in the past and would love to learn how the CUDA interface is implemented in Meshroom.

**Comment by natowi** [comment]
@edtechchrward Yes, the CUDA code in Alicevision (Meshroom>GUI) needs optimization. Search [Alicevision/Alicevision](https://github.com/alicevision/AliceVision/search?q=cuda&unscoped_q=cuda) for CUDA code.
Implementing and improving CUDA for DepthMap calculations is WIP [481](https://github.com/alicevision/AliceVision/issues/481#issuecomment-412322515). 
You are welcome to contribute.

**Comment by edtechchrward** [comment]
@Darker Sorry for causing confusion. The fact that my second GPU was ignored suggests that the code uses the "GUI" GPU as the "CUDA" platform as well (it does not look for a second GPU). From a programming perspective, when the same GPU is used for both GUI and CUDA, you have to consider that a bug may be caused by either mode of usage and possibly even the synchronization between the modes of usage. Or not ... bugs can be hard to find.

**Comment by Darker** [comment]
I still don't understand. Why does the window do anything with the GPU at all? I don't know much about GPUs, so I'm really confused here. Probably also worth noting is, that through feature detection and feature matching, I saw no GPU usage at all, when the window was minimized.

**Comment by Darker** [comment]
For me, depth map does not use GPU, and also does not really use CPU as much as possible:

![image](https://user-images.githubusercontent.com/5508988/51759044-93b1e200-20c7-11e9-82eb-51a7ef08d1ee.png)

**Comment by natowi** [comment]
@Darker some parts of the code are not fully optimized.

**Comment by fabiencastan** [comment]
Just to avoid misunderstanding from the discussion :

The usage you noticed is due to the 3d environment in qt, and we cannot do much about it.

It's not related to the usage of cuda in AliceVision.
