### ISSUE TITLE
Problem with scanning rooms

### ISSUE THREAD

**Issue by BTeaJoe** [alicevision/meshroom#415]
I tried to scan a small kitchen, but the result is, sadly, not good enough for being of actual use. Some objects are just placed at the wrong positions and most of the flat surfaces are rough instead. When I try to flatten the surfaces in Blender, there are small grey patches on the textures. The kitchen has some surfaces that are kind of glossy. Is this the source of the rather poor results or am I doing something wrongly? I used the default settings for processing, a rather good camera, and all images have the size of 5184x3456. 

Any recommendations for scanning rooms? 

Here is the result I got when I tried to compute only half of the room (182 images, most were reconstructed):
![image](https://user-images.githubusercontent.com/48351629/54025105-cd333e00-4199-11e9-86c4-a2ec2a5ba17a.png)

**Comment by natowi** [comment]
Flat, single colored or glossy surfaces are difficult to reconstruct. Considering this, your result is quite good. You can try reconstructing with high/ultra [settings](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters). For the misplaced area try to shoot some more images of the misplaced area (if possible) to give Meshroom more features to detect.

**Comment by hargrovecompany** [comment]
just out of curiosity, did you use a flash to take the photos?  
if so, the light source and shadows are different in every photo and that would make it difficult for the software to align features

**Comment by BTeaJoe** [comment]
![img_7340](https://user-images.githubusercontent.com/48351629/54044465-4d27cb00-41cf-11e9-8d54-7c50c902a03e.JPG)
most of it is not single-colored, but many surfaces have a glossy component as you can see. I did not use flashes while taking the photos. The light comes from outside, although curtains dimmed it a bit.
Thanks for giving advice... Next time I'll try to take even more photos in difficult regions, although I did already take more photos at that region.
But how about the rough modeled surfaces where they should actually be flat instead?

**Comment by hargrovecompany** [comment]
That's a tough one.  Maybe try again at night with no sunlight and the lighting come from behind you?   Several lamps spread apart from each other with a sheet or something to diffuse the light would help.

**Comment by hargrovecompany** [comment]
I'm pretty sure the "wrinkles" on the surfaces that are smooth occur because depth mapping is triangulating the same reflection of a given item as a feature in a different location on every image.  Think of it this way...a lit candle is on a polished marble table.  you walk around the table taking pictures of if from every angle.  The reflection of the flame is in a different position in every photo.  The marks inherent to the marble are static.  Both are identified as features.  The software compares the locations of the features and uses triangulation to determine how far those points were located away from the cameras used for that particular calculation.  Then move to the next sets of photos that overlap the one that was just calculated.  The reflection of the flame is in a different location again.
