### ISSUE TITLE
Gui crashes on meshing

### ISSUE THREAD

**Issue by Tedrizze** [alicevision/meshroom#430]
Hi,

whenever meshroom is on the stage of meshing, the GUI collapses while the command window stays open, finishing the mesh task and then closing itself too.

When i reopen Meshroom and i get " graph is being computed externally" message and need to delete the folders/files manually to get a chance to try again.
The mesh is beeing generated fine in the "Meshing" folder but meshrooms doesnt recognize this step as being completed.

I tried reducing the image resolution, and reducing the "Max Points" value in the Meshing node to 200.000 (from 5.000.000) still hasnt solved this issue...

Im kinda frustrated right now.

System Specs are:
Core i7-7820X
16GB DDR4-3200 RAM
RTX 2070 (8GB)

Thanks for the help in advance!

**Comment by AlexandrParkhomenko** [comment]
Please, send full command window log with output content

**Comment by chad123chad** [comment]
I had same issue did you ever fix it

**Comment by fabiencastan** [comment]
Sorry for having missed this issue.

You have a menu in the top-right of the graph editor to clean the external status:
![image](https://user-images.githubusercontent.com/153585/67140744-efc42400-f25d-11e9-9e29-f9eeb6e5d7d0.png)

Did you try to monitor the RAM to see if the problem comes from RAM or not?
Have you closed all other applications while computing? Your web browser for instance can be very RAM consuming.
Have you tried to also reduce the "Max Input Points"?
