### ISSUE TITLE
Crash -- Import Error: No module named encodings

### ISSUE THREAD

**Issue by Ev3ntHorizon** [alicevision/meshroom#446]
After downloading the Meshroom package and running the exe, I get the Fatal Python Error as in the title. Ive googled and cant find anything that works. Help!

**Comment by natowi** [comment]
Try running Meshroom as admin or reinstall python as admin. Check the Python PATH if there are any conflicts.

**Comment by Ev3ntHorizon** [comment]
Tried and tried. No dice!

**Comment by natowi** [comment]
I think this is a python config problem. This might help: https://stackoverflow.com/questions/42512817/fatal-python-error-on-windows-10-modulenotfounderror-no-module-named-encodings

**Comment by Ev3ntHorizon** [comment]
Tried this one too! Ive got the correct variables set and it gives the same error.

**Comment by natowi** [comment]
Do you have any special characters/non-ASCII characters in your Meshroom Installation path?
This is the last thing I can think of to check.

**Comment by Ev3ntHorizon** [comment]
E:\Meshroom :(

**Comment by Ev3ntHorizon** [comment]
Ok, I figured it out. Turns out the Meshroom install must have been corrupt...I re-downloaded and extracted and it worked.

**Comment by raisbecka** [comment]
Just in case anyone else runs into this issue... I had the same error message, and what worked for me was moving the files to a directory on the root of the C drive. Previously, the files were on my desktop, and because I am on Windows 11, my user folders are all on OneDrive. 

Check this and move the files off of a OneDrive-governed path if they are located there.
