### ISSUE TITLE
Restart Meshroom using prior cache

### ISSUE THREAD

**Issue by donox** [alicevision/meshroom#535]
Maybe I'm just missing it, but I've made a Meshroom run which dies for lack of memory in Texturing.  I have the Cache folder, but I cannot figure out how to restart Meshroom using that Cache.  Note that I had to relaunch Meshroom, so it doesn't know about the prior cache (that I can determine).  
Is there a way to tell Meshroom to reload a previous computation from a saved Cache without completely restarting?
Thx,
  --Don

**Comment by ChemicalXandco** [comment]
You must open the saved .mg file in meshroom (File -> Open) and the MeshroomCache folder that should be in the same directory will be loaded and the node progress recovered. 

If you did not save the project, the MeshroomCache folder is placed in a tempory location (C:/Users/<username>/AppData/Local/Temp on windows), and in order to retrieve the progress you must have a new project and import the exact images that were used before and assuming the node settings are the same the progress should be recovered.

**Comment by MrMitch17** [comment]
I'm having the same issue. I started a new project and saved the config.  Project crashed, and now its not loading any of the caches again.  The UIDs in the .md file do not match the UIDs in the folder structure.  I tried editing the .md file to match the UIDs, but no luck.  The UI still looks like its generating new UIDs when opening the modified .md file.

**Comment by fabiencastan** [comment]
One possible way to get this problem:
1/ drop images into meshroom
2/ save the scene
3/ change one parameter which invalidates the graph OR drag&drop one or more images
4/ launch the compute without saving the project
5/ get a crash or get meshroom killed by the os due to too much RAM usage

Now when you open meshroom again, you will retrieve the state of the last save.  The only way to retrieve your data is to remember and redo exactly the changes you have made after the last save...

**Comment by MrMitch17** [comment]
That might have been what happened. Its possible saved first, then loaded images.  I was able to sort of recover, by starting each node, then stopping that process, then copying the cache into that new folder.  It looks like that was able to restore the cache.

**Comment by GrahamT3D** [comment]
> You must open the saved .mg file in meshroom (File -> Open) and the MeshroomCache folder that should be in the same directory will be loaded and the node progress recovered.
> 
> If you did not save the project, the MeshroomCache folder is placed in a tempory location (`C:/Users/<username>/AppData/Local/Temp` on windows), and in order to retrieve the progress you must have a new project and import the exact images that were used before and assuming the node settings are the same the progress should be recovered.

I have run out of space on my C:\ drive at the texturing stage (after 12 hours meshroom render). Is ther a way I can move or reassign folder paths so that I can move the 40gb folder to my E:\ Drive?

**Comment by chaydock** [comment]
Not to necro an old post. But, this is still the top search hit for this topic and the answer could use some added explanation.

So, I too recently had a long render running where I didn't save prior and after running for about two weeks the PC had a forced shutdown (nothing to do with Meshroom for what it's worth). Not wanting to lose the nearly two weeks of work already completed, I found this thread trying to find a solution. Anyway... I tried kicking off a new render and then moving the output of the prior node cache into the new folder. Saving and restarting/loading the node turned green... but the next node in line would fail to pick up the data and process anything. After some playing around I noticed that the log files in the output folders are in plain text and have an initial dump of the settings that were used for that node. Matching the settings still from the last completed node didn't help, but I noticed while tinkering that the output folder name would change based on node settings. I assume this is some kind of hash of the settings. However, just picking the same settings on that node wasn't enough because the hash is also including any input folder names from upstream nodes (which are also some kind of hash). So... the end all solution was to go through each node one by one and look at the log files to match the node settings at each node up to the point of the crash. As I matched each setting in sequence, the output folders would match up exactly as their previous output folder names. There were a couple of nodes that the setting section said "unknown" blah blah blah rather than specifying a specific setting variable. So, those were a trial and error to match. Thankfully there weren't many of those and thankfully being drop down items to pick from it wasn't too hard to find the proper match.

Anyway... long story short... start from node one, find the log file for that node and match contained within. Once matched, the target output folder should match up too. Move to the next node in line... rinse and repeat... then SAVE! :) Close the project and re-open it and all your nodes up to that point should be green. You can then tweak subsequent nodes to your liking and continue processing where you left off from.
