### ISSUE TITLE
Drag and drop does not work.

### ISSUE THREAD

**Issue by ThimThim** [alicevision/meshroom#560]
**Configuration**
Version 2019.1.0-develop
Darwin 17.7.0 
Python 2.7.16
macOS 10.13.6

Drag and drop does not work.
I can not import photos or folder
 
[Bug.mov.zip](https://github.com/alicevision/meshroom/files/3426542/Bug.mov.zip)

**Comment by natowi** [comment]
As a work-around you can add images using the live reconstruction folder.

macOS is not officially supported. Did you follow the build process described [here](https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html)?

**Comment by ThimThim** [comment]
I followed what was written [here](https://github.com/alicevision/meshroom) 
(At the end of the page)

Here is the error message of the console:

```
/bin/sh: aliceVision_cameraInit: command not found
[2019-07-25 13:56:49,666][ERROR] Error while building intrinsics : Traceback (most recent call last):
  File "/Users/TM/meshroom/meshroom/ui/reconstruction.py", line 382, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "/Users/TM/meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 192, in buildIntrinsics
    subprocess.returncode, cmd)
RuntimeError: CameraInit failed with error code 127. Command was: "aliceVision_cameraInit  --groupCameraFallback folder --defaultFieldOfView 45.0 --verboseLevel info --sensorDatabase "" --output "/var/folders/d3/bjdj567n78b5c9tn7qmvsxy80000gq/T/tmpirfAC8/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "/var/folders/d3/bjdj567n78b5c9tn7qmvsxy80000gq/T/tmpirfAC8/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""
```

**Comment by hargrovecompany** [comment]
are you using a camera that's included already in the camera data base?  the info is included in the documentation.

**Comment by usrnamesllrdytkn** [comment]
I run meshroom in googles colab in python laptop
the process ends with:
RuntimeError: CameraInit failed with error code 127. Command was: "aliceVision_cameraInit  --sensorDatabase 
What can I do

**Comment by DenisS123** [comment]
Hello,

I got the same error message while trying to run meshroom from google colab.
Some files were missing in aliceVision/bin and aliceVision/lib.
There was a file named "aliceVision_cameraInit-2.0" in the bin folder but no "aliceVision_cameraInit".
When I double checked on my computer I found the missing files but didn't find them on the google drive. It is looking like the command "!tar xzf Meshroom-2019.2.0-linux.tar.gz -C ./meshroom" I typed did not extract some aliases for somereason.
You need to make sure that all the aliases are available in the folder aliceVision/bin and aliceVision/lib.

After adding all the files I got an other error message because the aliceVision binary and library files coudn't be executed. After checking out with
`!ls -l`
the files were in read/write mode mode but not in execution mode, so I added the execution mode with the following code:
`import os, stat
for fn in os.listdir("Meshroom-2019.2.0/aliceVision/lib"):
  os.chmod(fn, stat.S_IRWXU)
for fn in os.listdir("Meshroom-2019.2.0/aliceVision/bin"):
  os.chmod(fn, stat.S_IRWXU)
!ls -l`

I am not sure if my explanation was clear. Feell free to ask more if you need more explanations.
