### ISSUE TITLE
Node layout links structure

### ISSUE THREAD

**Issue by tibicen** [alicevision/meshroom#562]
Hi I've encountered some unusuall default node connections.

By default Nodes are often connected `Input` > `Input`. 
My proposal is to connect previous node `Output` > `Input`.
This is rather unusual, but of course it is nice to have that option, not making it more constrained. The problem is, the default option is hardly readable, and confusing. And of course connecting output from "previous" node is the would end in the same results: 
![obraz](https://user-images.githubusercontent.com/5797670/61938316-18a38880-af91-11e9-8dfd-46f560869e2a.png)
It is not only about only showed nodes, but principle.
What do you think about this small change?

**Comment by natowi** [comment]
I have thought about this, too.
https://github.com/natowi/meshroom_doc/blob/master/source/node_reference/connect-nodes/connect-nodes.rst

**Comment by tibicen** [comment]
I found the place responsible for this, and would like to work on it to fix this, if there are no one against it, anyone can give me a green light?

**Comment by natowi** [comment]
@yann-lty Any reasons on the current node layout?

**Comment by yann-lty** [comment]
I get why this can be confusing, but the idea was to keep a clear layout when starting to multiply variants. If we push your idea, we would have a link from CameraInit.output to all nodes until StructureFromMotion. And then StructureFromMotion.output to all nodes until the end of the pipeline.
If we stay in a simple pipeline, I guess this is okay. But I think this might make things harder to read in more complex use-cases:
**Input > Input (current implementation)**
![image](https://user-images.githubusercontent.com/1674646/61945678-db46f700-afa0-11e9-8326-eb9c15920137.png)
**Output > Input (proposed implementation)**
![image](https://user-images.githubusercontent.com/1674646/61945652-d124f880-afa0-11e9-875b-9d3f09c389fe.png)

But I totally agree on the fact that the graph editor would greatly benefit from UI improvements to make it more readable and better appreciate connections between nodes on a visual level.

**Comment by natowi** [comment]
How about an option to switch between both variants?

**Comment by tibicen** [comment]
> Thank you for the explanation. How about an option to switch between both variants?

I think that could leave some confusion. In my opinion default graph, should be consistent, and straight without any additional steps (like popus etc). I'm kind of guy: "Less buttons, less options -> more functionality".

I would stick with one option.

@yann-lty It is right that first example looks clean, but it confues how the nodes works. It just hides connection under the nodes. Second picture (however noodly it looks) shows real realtions, between nodes/folders/relations.

1. "Pass-through output" - that is just additional element that only func is to pass element through, that unnecesarry complication, and more options.
2. Current state - looks clean for noob/advanced user, but doesn't really show real relations.
3. Both variants - i would stick to one default option
4. After some thought I would still recommend "noodly" sollution with proper connection. It might look messy, but it could really help for newcomers to understand nodes relations.

P.S. I would also consider renaming "`input` and `output` for proper names. But I don't know if I should make separate issue for that?

**Comment by MightyBOBcnc** [comment]
The current implementation is visually clean, but it is very confusing and doesn't conform to the standard in other DCC programs.  I think the messiness (https://user-images.githubusercontent.com/1674646/61945652-d124f880-afa0-11e9-875b-9d3f09c389fe.png) would be preferable if it eliminates the confusion of inputs connecting to other inputs.  Messiness is just a fact of life in a complex node system.  Unreal Engine 4 example: https://i.imgur.com/QFV3D74.jpg

One thing that could be introduced to clean up messy node graphs would be reroute "nodes" like in UE4 (double click on a spline) or Substance Designer (alt+left mouse click).  These are simply control points that the user can insert to manually control the spline flow.  You can actually see a few of these points in the UE4 example above (points controlling the spline flow in the bottom left).  Here's a Substance Designer example: https://www.youtube.com/watch?v=gihP4nFiaLw

An alternative that might possibly be both clean and intuitive (but would require more work to implement) could be to enforce a grid in the node graph and instead of allowing the splines to be "noodles" force the splines connecting the nodes also follow the grid like in flow chart software (this example created with www.draw.io): https://i.imgur.com/5s0LudX.jpg

**Comment by tibicen** [comment]
Agree with @MightyBOBcnc, except constraint it to grid layout. 
I like to think that there are different people with different approaches. Wheather they are thinking linear, tree-like or even in circles. I would leave node layout flexibility, with a cost of messines.

I could try implement simple reroute node that handles one link `in` and many links `out`. As it is said I would recommend cleaning the inputs and outputs in groups, like:
`{ImageMatching.inputs.featuresFolder}`
`{ImageMatching.outputs.output}`
`{StructureFromMotion.outputs.extraInfoFolder}`
and rename all `input` and `output` sockets into proper names. Of course leaving the possibility to connect `input` to `input`.
Additionally create func to update all the old .mg files to new ones.

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/pull/612

**Comment by natowi** [comment]
This is a preview of the upcoming node design:

![mr](https://user-images.githubusercontent.com/8138537/104125062-a9704e80-5354-11eb-965c-fd7b4a61f9d0.JPG)

(pass-through node connections are dotted lines)

And it will be possible to create dependent node settings

![mr2](https://user-images.githubusercontent.com/8138537/104125263-e721a700-5355-11eb-967b-6adeeb91e6ab.JPG)

**Comment by natowi** [comment]
Closed by #612
