### ISSUE TITLE
Meshroom vs RealityCapture

### ISSUE THREAD

**Issue by ladiszlai** [alicevision/meshroom#585]
RealityCapture:

![test1](https://user-images.githubusercontent.com/6253595/62840565-f736e200-bc9c-11e9-85a1-e72f96460e1d.jpg)

Meshroom:

![test2](https://user-images.githubusercontent.com/6253595/62840566-0453d100-bc9d-11e9-9a68-c86860ed5238.jpg)

Am I did something wrong or is this just the quality of this program ?

**Comment by Dok11** [comment]
Several month before I did similar comparison and in my case (interior photos) worse result was from RealityCapture.
I think the differnece in the default settings. And in your case default settings of RealityCapture better match for your dataset then in MeshRoom.

For detailed work you sholud learn many settings of reconstruction parameters no one program will do good result just by one button.

**Comment by ladiszlai** [comment]
@Dok11 Which settings should I change ?

**Comment by fabiencastan** [comment]
See here:
https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters
The first thing to try is to adjust the DescriberPreset on the FeatureExtraction node and check the number of cameras reconstructed after the StructureFromMotion node.

**Comment by ladiszlai** [comment]
@fabiencastan 
![test3](https://user-images.githubusercontent.com/6253595/62856158-6ee42b80-bcf4-11e9-8740-1d41a1ac140a.jpg)

ehmm... no sorry, this program is useless lmao xDD

**Comment by natowi** [comment]
@ladiszlai Some objects don´t work out of the box and require some work (optimizing capturing and meshroom settings - the regular pattern could be an issue). 
To compare RC and MR try known sample datasets.

**Comment by fabiencastan** [comment]
Hi @ladiszlai,
This place is not a forum but an issue tracker to report problems and try to fix them. Please have a look at the [code of conduct](https://github.com/alicevision/AliceVision/blob/develop/CODE_OF_CONDUCT.md).

This type of error is often due to a problem with the camera parameters. Please check the metadata/sensor database: https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database. It could be an error in the DB for your camera device.

**Comment by hargrovecompany** [comment]
what settings did you use?  try it with default settings
