### ISSUE TITLE
Lock camera intrinsics

### ISSUE THREAD

**Issue by zengletian1491** [alicevision/meshroom#645]
**Describe the problem**
I would like to lock the intrinsics of the camera(i.e., camera matrixf) and keep them invariant during the pipeline. Is this process possible to be implemented? How can I implement this process?

**Comment by fabiencastan** [comment]
After dropping your images into Meshroom, you can go on the CameraInit node and open the "intrinsics" group and check the "lock" option on the intrinsic you want to lock.
![intrinsicLock](https://user-images.githubusercontent.com/153585/65232324-3c86d480-dad1-11e9-8498-4e395f677328.png)

As an other way to do it, you can also lock **all** the intrinsics on the SfM node:
![sfmIntrinsicLock](https://user-images.githubusercontent.com/153585/65232616-bdde6700-dad1-11e9-94c6-e0fc6d015456.png)

**Comment by SBCV** [comment]
Is it also possible to lock only specific intrinsic parameters? 
For example: Keep the provided principal point fixed, while optimizing focal length and radial distortion? (In other SfM tools I found that freezing the principal point is usually a good idea)

**Comment by SBCV** [comment]
OpenMVG has an option called [refineIntrinsics](https://openmvg.readthedocs.io/en/latest/software/SfM/IncrementalSfM/) that allows to define which intrinsic parameters are refined and which are kept constant. 
According to [this rst file](https://github.com/alicevision/AliceVision/blob/develop/docs/sphinx/rst/software/SfM/IncrementalSfM.rst) the "refineIntrinsics" option in AliceVision has been changed. 
 Has this functionality been dropped without replacement?

**Comment by fabiencastan** [comment]
@SBCV The documentation of these rst files are not valid at all. We have to re-write them completely.

I do not understand what is not clear in my previous message in this thread: "refineIntrinsics" is now reversed with force lock intrinsics option.

You cannot only lock the internal camera parameters globally. But by default the pipeline only refine
the principal points when we have enough cameras to do it.

**Comment by SBCV** [comment]
@fabiencastan Thank you for the quick answer! 
Your previous post (with the screen shots) is clear. 
I just wanted to know, if it is possible to control the locks of spefic intrinsic parameters on a more fine-grained level, e.g. lock only the principal point of a specific sensor. I think such a feature would be very useful, since many cameras are symmetric, which is why the principal point in the corresponding images lies at the image center.
As far as I understand your last post, this is currently not possible. Do you think that such a feature (i.e. manually locking the principal point) will be introduced in a future version?

**Comment by fabiencastan** [comment]
We can imagine to change the boolean lock into an enum to expose multiple options.

**Comment by SBCV** [comment]
That would be fantastic!
