### ISSUE TITLE
Installing Meshroom under Windows/Ubuntu with Anaconda3

### ISSUE THREAD

**Issue by SBCV** [alicevision/meshroom#658]
I'm unable to start Meshroom following the [installation instructions](https://github.com/alicevision/meshroom/blob/develop/INSTALL.md).

As recommended, I executed at some point `set PYTHONPATH=%CD% && python meshroom/ui`, which caused the following error: 
> qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: minimal, offscreen, windows.

Adding the following environment variable `QT_QPA_PLATFORM_PLUGIN_PATH` with the path to the Pyside2 Plugin folder. E.g. 
> QT_QPA_PLATFORM_PLUGIN_PATH=C:\Users\<user>\AppData\Local\Continuum\Anaconda3\Lib\site-packages\PySide2\plugins\platforms

fixed this problem. 
Executing `set PYTHONPATH=%CD% && python meshroom/ui` again, causes the following error message:

> [2019-09-26 11:59:06,642][WARNING] QQmlApplicationEngine failed to load component
[2019-09-26 11:59:06,642][WARNING] file:///C:/Libraries/Meshroom_build/meshroom/meshroom/ui/qml/main.qml:2 plugin cannot be loaded for module "QtQuick.Controls": Cannot load library C:\Users\<user>\AppData\Local\Continuum\Anaconda3\Library\qml\QtQuick\Controls\qtquickcontrolsplugin.dll: The specified procedure could not be found.

The line `main.qml:2 ` contains `import QtQuick.Controls 2.3`

Did someone experience this before?

**Comment by natowi** [comment]
See https://github.com/alicevision/meshroom/issues/563

**Comment by SBCV** [comment]
I've seen this issue before. 
My Pyside2 version is `5.13.0` and the script is already using `import QtQuick.Controls 2.3`. 
At which comment of the issue are you refering to?

**Comment by natowi** [comment]
> 
> 
> Side note about 5.13.0 on Windows that we should not forget: the assimp sceneparser plugin is missing from prebuilt binaries, which prevents OBJ files to open in the 3D viewer. The missing library (assimpsceneimport.dll) must be copied from a previous PySide2 installation (Lib/site-packages/PySide2/plugins/sceneparsers). See https://bugreports.qt.io/browse/PYSIDE-1005.

**Comment by SBCV** [comment]
What I did now

- Running `pip install Pyside2==5.12.0`
- Copying `C:\Users\<user>\AppData\Local\Continuum\Anaconda3\Lib\site-packages\PySide2\plugins\sceneparsers\assimpsceneimport.dll` to `some\location`
- Running `pip install Pyside2==5.13.0`
- Copying `some\location\assimpsceneimport.dll` to `C:\Users\<user>\AppData\Local\Continuum\Anaconda3\Lib\site-packages\PySide2\plugins\sceneparsers`

Running `set PYTHONPATH=%CD% && python meshroom/ui` throws the same error message as before.

**Comment by SBCV** [comment]
I experienced similar issues using **Ubuntu** and Anaconda3. It seems that Anaconda is messing up some Pyside2 related .dll / .so files.  One reason could be that PyQt and other QT related packages are installed by default.

I **fixed it** by using [Miniconda](https://docs.conda.io/en/latest/miniconda.html) for Python 3.7.

In this case it was also not necessary to adjust `QT_QPA_PLATFORM_PLUGIN_PATH` or something else.

I don't know, but I have the feeling that a corresponding note should be added to the install instructions.

**Comment by Caine78** [comment]
> > Side note about 5.13.0 on Windows that we should not forget: the assimp sceneparser plugin is missing from prebuilt binaries, which prevents OBJ files to open in the 3D viewer. The missing library (assimpsceneimport.dll) must be copied from a previous PySide2 installation (Lib/site-packages/PySide2/plugins/sceneparsers). See https://bugreports.qt.io/browse/PYSIDE-1005.

Hi natowi,

That will sound probably funny for most of the readers, but honestly, read it. If you don't like the long stories, just read the bottom line. Remember your first encounter with Python or a computer. If you were very confident and had mathematical mind it probably went very smoothly. Now listen to this.

I was given my first computer 35 years ago. When I was 6. I had a few breaks, due to the old equipment that wasn't giving me fun, plus 23 years ago, there was no GitHub, stacktrace, YouTube or even Google. We had a BBS. I come from Poland and we had to dial +48202122 (u:ppp, p:ppp). It is still working today. Speed 10kb/s if you were lucky max 35kb/s/ I just ended my job in Support for medical software development, as it was or at all challenging (reset password, that actually use can do himself), or something ridiculously bizzare. I have over 20 years of experience in IT. 2 degrees. Foundation Degree in Applied Computing (like everything) and BSc in Games Design.

Would you kindly explain it to me, why I have to clue about what you are talking about? (It is not you, I literally cannot follow any of the advice when Python is involved). That is why I hate Python and I go around as far as I without it. Now I can see that unfortunately, I will not get away without it. I love the results that the software produces, but I never managed to get anything working. I am having a lot of trouble with photogrammetry, but I will not give up that easily.

When you guys type the advice for people like me, please understand that I am a complete programmatic moron. What do I need to open to find this file? I downloaded all Pyside's from the website and I cannot find anything with that name. Where do I need to copy it? Somebody mention to recompile it. How to recompile it? In which software? Which file do I need to open.?  

It would be really awesome if you could teach us guys a little. I am ending up with 40 pages open, 10 windows explorers and at the end, nothing is working. Lack of knowledge. I know, but I am a Windows user and I will be just installing for a first time Linux on my 2nd PC. To learn it.

**Comment by natowi** [comment]
@Caine78 Sorry for answering so late, but here is a more detailed explanation: there was a bug in pyside 5.13 that excluded the assimpsceneimport.dll from the final build. So one had to install pyside 5.12, go to the directory and backup the dll. Then you could update to pyside 5.13 and insert the old dll in the new folder. So basically a workaround. This workaround was for Windows only, that´s why you could not find the assimpsceneimport.dll on Linux.
All of this should be solved by now with our latest Release for Windows and Linux.

Regarding Python: in Meshroom Python is only used for the GUI, as pyside2 (QT for python) allows easy GUI design.
Alicevision is written in c++, maybe something you are more familiar with. If so, you are welcome to contribute.
