### ISSUE TITLE
How can i scan a object that can hold up it self like a game case 

### ISSUE THREAD

**Issue by TheSkripterDK** [alicevision/meshroom#743]
So how would Is be able to photoscan a game case like this from all sides
![image](https://user-images.githubusercontent.com/29629145/71325871-5c280180-24f3-11ea-94f6-5a7382fa5287.png)

since it cant stand up on its own

**Comment by SquidLord** [comment]
Get yourself a piece of sticky clay, Play-Doh, or the like, put it on the tip of a stick about a foot long, maybe 6 inches if you have a smallish table to put it on, and then use that elevation to be able to get some shots obliquely underneath. This works for lots of things with undersides that you really want to capture.

Don't make the mistake of having a featureless backdrop, however. If you do so, you're going to lose a lot of potential depth cues for reconstruction. You can always take out those extra points after the point cloud has been made.

Once you have a completed model, edit out the place where it is joined to the stick at the bottom which should be relatively easy because it's a pretty flat surface with just a crease and you're ready to go.

**Comment by natowi** [comment]
Note: A game case is the type of object that can be build faster in a 3d modelling software than using photogrammetry. There are even game case 3d models that can be used.
