### ISSUE TITLE
 [question]3D model City model ot be generated

### ISSUE THREAD

**Issue by tub-sgg** [alicevision/meshroom#787]
**Describe the problem**

Is it possible to generate a city model using some screenshots of a city from google earth mesh model?And another question is if I know the cameal's location(that's I have the gps data for the cameras),where should I insert the data to generate the real model of a  city??

**Comment by natowi** [comment]
It is possible to use screenshots for reconstruction, but the results might not be as expected. 
GPS is not (yet) supported by Meshroom.

You might want to search for open data (aerial survey images, lidar scans,...) for the region of interest to get high quality data.

**Comment by tub-sgg** [comment]
so you mean I can not set the position for the camera in meshroom?

**Comment by natowi** [comment]
It is possible, but requires work https://github.com/alicevision/meshroom/issues/300

**Comment by tub-sgg** [comment]
can you specify more detail about that?I  have data like this
"coordinate":{"latitude":52.,"longitude":13,"altitude":279},"fovVertical":20},{"position":{"x":377,"y":89,"z":5},"rotation":{"x":242.3,"y":-70.45,"z":-2.35},
I know  all the position of the cameras,so which file I need to create and how can I do the settings to import the data for camera? Can you offer a reference(more details about that) thanks @natowi

**Comment by natowi** [comment]
I am working on a wiki page for the faq, but have not yet figured this topic out entirely.
You can try this https://github.com/alicevision/meshroom/issues/788#issuecomment-587478786

**Comment by tub-sgg** [comment]
I ckeced the links but I din not find which file I need to modify to insert the camera's location and orientation???

**Comment by natowi** [comment]
Reconstruct a few images with the default graph, then open the StructureFromMotion node folder. The cameras.sfm file contains the pose (rotation, center) for each image. You can use the file structure to create your own sfm file (the sfm files are bsically json files). The rotation values need to be provided as quaternion
https://github.com/alicevision/meshroom/blob/bc1eb83d92048e6f888c4762c7ffcaab50395da6/meshroom/ui/reconstruction.py#L293
https://math.stackexchange.com/questions/893984/conversion-of-rotation-matrix-to-quaternion
https://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/

But due to the gps inaccuracy this might not generate useful results.

**Comment by natowi** [comment]
@tub-sgg Check out https://github.com/eliemichel/MapsModelsImporter
