### ISSUE TITLE
[question] Is it possible to scan a flooded room?

### ISSUE THREAD

**Issue by Burke9077** [alicevision/meshroom#796]
I've used meshroom before to scan an individual object with success. I'm wondering if it's possible to scan an entire room. Below is a photo of a basement I visited and would love to recreate with meshroom if possible. 

![download_20200221_131503](https://user-images.githubusercontent.com/6282442/75065596-bec75a80-54ae-11ea-86fa-bcfce0917e9e.jpg)
![download_20200221_134331](https://user-images.githubusercontent.com/6282442/75066286-2f22ab80-54b0-11ea-8f0b-a2092d13f0dc.jpg)

This is complicated by the room being flooded with light reflections causing issues with the small dataset I started working with. I won't be able to change the lighting conditions in this room. 

If it is possible to actually reconstruct even a bit of this cave I would like to return and take the right number of photos with better gear than just my phone. 

Would using a two+ camera rig with connected shutters help?
Would it be better to crop out the light reflections on the water?

It would be great to know if this isn't reasonably possible since it would take hours to take the photos alone.

**Comment by natowi** [comment]
This is a really complicated scene. Laser scanning would be the better choice here.
However you can try the following to improve the photogrammetry reconstruction:
Avoid light and water reflections. The first image is not too bad. A polarized filter can additionally reduce reflections. Move for each image to a different location and orient your camera in such a way that the reflections are not in the image.
There are also many good guides for capturing images for photogrammetry, use them for your preparation.

**Comment by Burke9077** [comment]
Perfect! Thank you for the advice. I am actually able to walk around, it's a local swimming hole. I suppose I can take photos of the water and walls without disturbing the water from ~7 or so locations and then handle the shots of the ceiling by swimming to various points. 

I don't think I'll be able to procure a laser scanner so I'll have to make due with photos that don't include the refractions as you say.

**Comment by hargrovecompany** [comment]
The reflection of the light off of the surface of the water will be a
killer.  maybe you can position the shots so that there are no shots with
more than about 1/8th of the image has water.  Also, you MIGHT be able to
position your camera so that the lighting is more or less behind you....and
there would be no reflection of light visible on top of the water.
Cropping might work.  Regardless, to get a good 3d you'll need to take a
lot of photos from a lot of angles.   As an example, the stelactite that's
solid from top to bottom....you'll need to take images from all the way
around it to make it render to 3d without holes.

Also, for the water....can you use and underwater camera?
