### ISSUE TITLE
How to get dense point cloud in .ply format?

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#803]
Hello,

At the moment I am working in the generation of point clouds and I need to export the dense point cloud results that meshroom give me in .ply format instead of .abc. I know that I can export the sparse point cloud using the ConverSfMFormat. Is there a similar approach to the dense one?
I am working with Ubuntu 18

**Comment by natowi** [comment]
Create  a new ConverSfMFormat and paste the path to the dense point cloud in the input path field.

**Comment by natowi** [comment]
![save](https://user-images.githubusercontent.com/8138537/75274327-f6156e80-5802-11ea-9a85-19fdb483ddf2.JPG)

**Comment by bgpantojar** [comment]
This was the result I got.

![Screenshot from 2020-02-25 17-34-09](https://user-images.githubusercontent.com/35929939/75274344-ff9ed680-5802-11ea-96d8-06c0024aabc2.png)

**Comment by natowi** [comment]
You used the Meshing output not the OutputDensePointCloud.
Create a new ConvertSfMFormat node, open the Meshing node and copy the OutputDensePointCloud path to the ConvertSfMFormat input.

**Comment by bgpantojar** [comment]
Many thanks for your patience and replies. I am using the OutputDensePointCloud as you can see in this pics.
Information of  meshing Node:
![Screenshot from 2020-02-25 20-47-41](https://user-images.githubusercontent.com/35929939/75281767-21eb2100-5810-11ea-88d3-60e7beb9f4ae.png)

Information of ConverSfMFormat Node:
![Screenshot from 2020-02-25 20-45-02](https://user-images.githubusercontent.com/35929939/75281830-41824980-5810-11ea-829a-24dbb4ac45e2.png)

Thanks also for the tip related with the dataset

**Comment by Cesco-11** [comment]
Hello 

I'm new on Meshroom, I'm trying to do the same and export a dense cloud point here but I think I lost a step.
I used ConvertSfMFromat Node and copied inside the Output Dense Point Cloud from Meshing Node.
But there is not in the folder any .PLY file.
Also I connect the output from Meshing folder inside the input ConvertSfMFromat, becasue I try without connect them but it generate an error in compute.
What I'm doint wrong?

Thank you a lot

**Comment by natowi** [comment]
@Cesco-11 @bgpantojar You don´t need to copy the paths (I mixed the answer up with another issue I was answering to, sorry for that). The conversion option is not available in 2019.2 but you can download

[ConvertSfMFormat.txt](https://github.com/alicevision/meshroom/files/4745279/ConvertSfMFormat.txt)
rename it to ConvertSfMFormat.pyc and place it in Meshroom-2019.2.0\lib\meshroom\nodes\aliceVision

Now you can use the "unknown" option that will include the point cloud in the conversion output.
![conv](https://user-images.githubusercontent.com/8138537/84018672-8fb2f700-a980-11ea-819e-8838c30f924e.JPG)

This will be included in the next release, which will be published soon.

**Comment by Cesco-11** [comment]
Hello!

Thank you for your reply,

Can I connect directly the output from the Meshing node to ConvertSfMFormat? and after compute only the noce?

Thank you again

**Comment by natowi** [comment]
yes

**Comment by Cesco-11** [comment]
It worked perfectly
Thank you a lot for your help.
Meshroom is amazing!

**Comment by infrared595** [comment]
Hi All,

I've run the StructureFromMotion (SfM) node resulting in a colorized point cloud like this:

![image](https://user-images.githubusercontent.com/60047966/85734107-a8e3d380-b6f4-11ea-9ee3-accb5beab072.png)

The SfM solve returns the following stats:

![image](https://user-images.githubusercontent.com/60047966/85733558-3115a900-b6f4-11ea-9783-95f9d143082b.png)

I have linked the output from the SfM Node to an 'ExportColoredPointCloud' Node, which I have then in turn outputted to a 'ConvertSfMFormat' Node in order to export the data in .ply format (for onward use in Meshlab).

In Meshlab, only 548 vertices are pulled through, as opposed to the 255,590 points in Meshroom:

![image](https://user-images.githubusercontent.com/60047966/85734876-4212ea00-b6f5-11ea-8d50-6f5b2c5c9e11.png)

Also, the RGB value of all the points is set to (R)0 (G)255 (B)0 i.e. green:

![image](https://user-images.githubusercontent.com/60047966/85735363-7f777780-b6f5-11ea-8194-1217defb4538.png)

Please could a kind soul assist me with pulling out a full colorized from Meshroom that I can use in Meshlab?

Many thanks!

**Comment by natowi** [comment]
@infrared595 https://github.com/alicevision/meshroom/issues/803#issuecomment-640510483

**Comment by infrared595** [comment]
Hi natowi,

Thank you for getting back to me so quickly - much appreciated!

My apologies, I should have included a screenshot of that step - to the best of my knowledge, I believe I have already followed the advice in Comment #803:

![image](https://user-images.githubusercontent.com/60047966/85770472-da6b9780-b712-11ea-95a2-3c4e552438af.png)

Many thanks!

**Comment by infrared595** [comment]
Hi natowi - might you be able to provide me with some further assistance please because I haven't been able to resolve unfortunately. Many thanks!

**Comment by natowi** [comment]
@infrared595 you don´t need the ExportColouredPointCloud node for SFM export.

Sparse point cloud
![img666](https://user-images.githubusercontent.com/8138537/87027073-e8262000-c1dc-11ea-9572-5774eec8d825.JPG)

Dense point cloud (same convertsfmformat settings)
![img777](https://user-images.githubusercontent.com/8138537/87027075-e8beb680-c1dc-11ea-8a17-41bb94a07530.JPG)

**Comment by AnnaNormant1** [comment]
Hey guys! i have an issue with exporting point cloud. I wanted to create a point cloud of my room, so i used photogrammetry technique. The problem is when i'm exporting the result according to the method described in this article https://www.programmersought.com/article/29634779521/ in the blender with the Point cloud visualizer add-on its says that there is no vertex normals. Please help me! what should i do?
<img width="790" alt="Снимок экрана 2021-10-19 в 01 45 06" src="https://user-images.githubusercontent.com/92762165/137816931-5acf0070-e942-461e-abf0-3b6c4ad13bab.png">
![zsWmQ-8e8-U](https://user-images.githubusercontent.com/92762165/137816957-3de945ac-6c8d-4507-b14e-cf58189d3c9e.jpeg)

**Comment by bestcsuer** [comment]
Hi，
I just want to get the scene pointes .ply file without the camera position points，what can i do to remove it?
thanks a lot.
