### ISSUE TITLE
White Object lost in mesh

### ISSUE THREAD

**Issue by ToddVG** [alicevision/meshroom#856]
I am trying to map a part on my Dash.. and to assure that there was no glare i read that spraying it with a powder ( I used Foot spray) would help. I took tons of Pictures with a Canon digital cam and with my New Iphone 11 pro Max. the Iphone seemed to take clearer pictures, so I used the 231 pictures from the phone and ran it thru Meshroom

The problem is that i basically lost the part i was trying to map, see screen shot from meshroom and Meshlab
![image](https://user-images.githubusercontent.com/47824830/79247323-60807d80-7e48-11ea-9edd-ca8f5138b93a.png)

![image](https://user-images.githubusercontent.com/47824830/79247378-7130f380-7e48-11ea-8d1a-a63ba0942290.png)

I am looking for any insight at all to my problem... thanks and please stay safe out there

Todd

**Comment by curtthemartian** [comment]
Unfortunately this software isn't great with monochrome objects.   If you had other colors in there, or something to help it identify contours with a contrasting system it would work better.   Same happens when trying to do it against glass or in my case walls.  
The more contrast it has the better the quality.  
I am trying to model my childhood home before I have to leave.   Works better than anything else I have used that is free, but I am looking to augment it with something else.

**Comment by NexTechAR-Scott** [comment]
It's a flat featureless object.

Understand that photogrammetry is 3d connect the dots.

Without detectable features there are no contributions to the point cloud that result in geometry.

That is not a meshroom exclusive challenge, it's just the way this works.

In the large image window hover bottom left and Display Features, the issue will be self revealing.

**Comment by tkircher** [comment]
You were definitely on the right track making it matte to reduce the glare. Like the above comment explains, there have to be consistent features for the feature detector to identify in order to reconstruct the object. The number of identifiable features directly translates to the number of points in the reconstructed point cloud, which is what's used to make the final mesh. Make sure it's not the same color as the background, then scribble on it with markers, paint camo by hand, spray paint it from a distance to make a speckle pattern, whatever. When you have your mesh, throw away the textures since your original object was monochrome, and you get a clean-ish model.
