### ISSUE TITLE
 Camera Matrix and Projection Function

### ISSUE THREAD

**Issue by germanroserop** [alicevision/meshroom#857]
Hello,

I am just starting in the computer vision world and using your software to learning it. I was wondering if is possible to reconstruct the camera matrices P of each picture used in the model generation. In the file cameras.sfm, I found information about the intrinsics and poses that you can see as follow:

![Screenshot from 2020-04-15 20-28-10](https://user-images.githubusercontent.com/63745005/79374511-aa0bbe00-7f57-11ea-8f33-e8e537fc8e1b.png)
 
I would like please if you can confirm me the next if possible. I think that with that information:
K = ([[6.98383437e+03, 0.00000000e+00, 2.55511212e+03],
       [0.00000000e+00, 6.98383437e+03, 1.77451749e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
R = [-0.64574673, -0.39907529,  0.65096088],
       [ 0.52752249,  0.38318831,  0.75821286],
       [-0.55202461,  0.83300998, -0.03692141]]
t = [[-1.47528776],
       [-1.67349586],
       [ 2.01149779]]
So, I could get P as P = K [R|t] ?

I would like to try to triangulate some points detected manually in two pictures using their camera matrices P by using SVD decomposition, like this:
def triangulate_point(x1,x2,P1,P2):
   """ Point pair triangulation from
   east squares solution. """
   M = zeros((6,6))
   M[:3,:4] = P1
   M[3:,:4] = P2
   M[:3,4] = -x1
  M[3:,5] = -x2
   U,S,V = linalg.svd(M)
   X = V[-1,:4]
   return X / X[3]

I am sure you have a function to do the triangulation. Could you please let me know which is that function and where I can find it?

Thanks and sorry for any inconvenience.

P.S. I got this model with your program. It is great. Thanks again.
![Screenshot from 2020-04-15 20-38-28](https://user-images.githubusercontent.com/63745005/79375556-16d38800-7f59-11ea-8154-659c9cb0c896.png)

**Comment by simogasp** [comment]
Hi,
* K is correct.

* R is not correct as it is saved in column-major order, so you basically have to take the transpose of what you got.

* t is not correct: the vector is the center C of the camera as in
```
0 = [R t] [C 1]^T = R C + t 
```
so that t = -RC

* for the triangulation of 2 views https://github.com/alicevision/AliceVision/blob/199a75f52d02cc2ce2a3ff267ae9881cc8ae365b/src/aliceVision/multiview/triangulation/triangulationDLT.cpp#L15
for N views
https://github.com/alicevision/AliceVision/blob/199a75f52d02cc2ce2a3ff267ae9881cc8ae365b/src/aliceVision/multiview/triangulation/Triangulation.hpp#L29

Note that meshroom is just a python UI for the underlying library that is AliceVision (C++).

Also, if you want to triangulate the points be sure you use the undistorted images, otherwise you need to undistort the points before calling those functions.
The distortion parameters are the 3 `distortionParams` below the focal length, and again you have functions to do that if necessary

**Comment by germanroserop** [comment]
Hello,

Thank you very much for your reply. It has helped me to understand better. I suppose that the distortion parameters (k1,k2,k3) follow the distortion equation L(r) = k1 + k2*r + k3*r (r^2 = x^2+y^2).

Knowing now about AliceVision, I just have tried to build it but found a lot of trouble. Do you know maybe if I can use its functions just from the binaries that are contained in the meshroom release?

Thanks again.

**Comment by natowi** [comment]
> Knowing now about AliceVision, I just have tried to build it but found a lot of trouble. Do you know maybe if I can use its functions just from the binaries that are contained in the meshroom release?

You can use the Alicevision binaries from the Meshroom release if you want to run AliceVision from the CLI https://github.com/alicevision/AliceVision/wiki/CLI-Parameters

If you are on Windows and need the exe, dll, ._lib and .exp_ files, take a look at
https://github.com/alicevision/AliceVision/wiki/Windows-Snapshot-Builds

**Comment by simogasp** [comment]
> Thank you very much for your reply. It has helped me to understand better. I suppose that the distortion parameters (k1,k2,k3) follow the distortion equation L(r) = k1 + k2r + k3r^2 (r^2 = x^2+y^2).

 L(r) =(1. + k1*r^2 + k2*r^4 + k3*^r6)

see here https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/camera/PinholeRadial.hpp#L161

And yes, if you have the binaries of alicevision you can either use the executable or build your own code and link with alicevision

**Comment by germanroserop** [comment]
Hello,

Thanks very much for the help. I just have another doubt related with the undistortion of points. I am so sorry for taking your time. 
Until the moment, I have used two pictures and the cameras meshroom provide to triangulate four points (with distortion). (red points are the points selected)

![Screenshot from 2020-04-21 19-04-46](https://user-images.githubusercontent.com/63745005/79892767-4b38bf80-8403-11ea-89d2-4aa93505d21d.png)
 as shown in the images.

The results are not accurate, and I assume one reason is because I have not undistort the points.
Looking in your codes you have this function:
https://github.com/alicevision/AliceVision/blob/d7a737f5d8b4ae32ca5f389c8266c49c4e733894/src/aliceVision/camera/PinholeRadial.hpp#L167
And according to the next line the coordinates have to be normalized.
https://github.com/alicevision/AliceVision/blob/d7a737f5d8b4ae32ca5f389c8266c49c4e733894/src/aliceVision/camera/PinholeRadial.hpp#L153
In the next script is mentioned that the normalization follows the Algorithm 4.2 from HZ book.
https://github.com/alicevision/AliceVision/blob/d7a737f5d8b4ae32ca5f389c8266c49c4e733894/src/aliceVision/multiview/conditioning.hpp#L16
At that point I got confused because according that algorithm I would have to do that all the points (I think here are those used to do the camera construction) should have origin (0,0) with average distance (2^.5).

In my case, that only I select 4 points, how can I normalize them?

Thanks again and sorry for any inconvenience.

**Comment by simogasp** [comment]
They are different types of normalization and there is maybe a bit of confusion in the terms.

In the context of camera coordinates, distortion etc, the `normalization` refers to the (normalized) camera coordinates as opposed to pixel coordinates.
Pixel coordinates are the coordinate of the pixel you pick in the images. These coordinates can be transformed into normalized camera coordinates by multiplying by the inverse of K, thus obtaining points that lies on a plane at f=1 distance from the origin. These points are basically the pure projections of 3D points on the 3D plane z=1.

To perform these operations back and forth you have two methods, `ima2cam()` and `cam2ima()`. But (and sorry if I misled you in the previous answer) you can just use `get_ud_pixel()` to undistort the point in pixel coordinates (ie as input you give pixel coordinates of your point and it returns pixel coordinates of the undistorted point)
https://github.com/alicevision/AliceVision/blob/d7a737f5d8b4ae32ca5f389c8266c49c4e733894/src/aliceVision/camera/PinholeRadial.hpp#L110

As for the triangulation, the normalization there is the data normalization, ie given a set of points it scales them down so every dimension is in the range eg [-1 1] to avoid numerical errors due to different orders of magnitude in the values of each dimension.
So you don't care about that normalization, it is something happening inside, you just need to feed the undistorted points

**Comment by germanroserop** [comment]
Thanks very much. Now, all seems more clear. I have got another question now. Do you do something extra related with displacements of the correspondences before to create the point cloud file? I am asking this, because I have used the camera information given for the camera file and used it to project the points you can see in the next picture.

![Screenshot from 2020-04-27 13-58-21](https://user-images.githubusercontent.com/63745005/80370078-a3524480-888f-11ea-8525-b9c3f061b666.png)

I just projected the coordinates of that 4 points together with the point cloud I got from meshroom and saw that they did not match as you can see in the next picture. (in the red mark are the projected points and in the green one the location where they should be.)

![Screenshot from 2020-04-27 13-52-29](https://user-images.githubusercontent.com/63745005/80370212-f88e5600-888f-11ea-946f-82e6dc62ae9d.png)

Do you have any idea what could have happened? or maybe what I am missing to project the points?

**Comment by germanroserop** [comment]
Hello,

I just solve the problem. It was just a problem in my codes.

Thanks!
